### ISSUE TITLE
Is it possible to add styles to an existing className on an element?

### ISSUE THREAD

**Issue by seanmcquaid** [facebook/stylex#103]
**Is your feature request related to a problem? Please describe.**
When utilizing some component libraries they utilize their own classNames as a means for allowing developers to customize their components. 

**Describe a solution you'd like**
As it stands, I am not seeing a great way how to do this in the docs. I initially looked at pseudo-classes and tried a similar approach with an existing classname on an element but I ran into some compilation issues. I am curious if this is even possible with StyleX?

**Comment by weti09** [comment]
Can you demonstrate this with an example? Do you want to add CSS to a class without using StyleX? Do you want to set a class while giving the element the StyleX.props?

**Comment by seanmcquaid** [comment]
So sorry for the confusion! I would love to extend/override the styling of a child element with StyleX. For example, in styled-components you can do something like this with selectors: 

```
const NewComp = styled.div`
    .child-label {
       color: red;
    }
`
```

Maybe something like this in StyleX

```
const styles = stylex.create({
  container: {
    color: {
      default: 'red',
      ".classNameInChildComponent": 'blue',
    },
  },
});

function App() {

  return (
    <div {...stylex.props(styles.container)}>
      <ComponentFromLibrary className="classNameInChildComponent">Hello World</ComponentFromLibrary>
    </div>
  );
}

export default App;

```

**Comment by seanmcquaid** [comment]
But in the case of a deeply nested child within that CustomComponent, I don't think those override styles passed this way would make it's way down, correct?

**Comment by weti09** [comment]
Yea, I saw your edit too late. I don't really know if it's working like that. I guess you either have to try it out or give a minimal example.

**Comment by necolas** [comment]
You can read about why StyleX doesn't support those kind of patterns as they break encapsulation and the kind of guarantees StyleX is designed to provide to component and app developers: https://stylexjs.com/docs/learn/thinking-in-stylex/#encapsulation

**Comment by seanmcquaid** [comment]
Thank you so much for sending this part of the docs over @necolas, totally understand this breaks some paradigms ya'll are trying to achieve! I will close this issue. Thank you for everything you and your team are doing!
