### ISSUE TITLE
[Webpack Plugin] Support add [hashcontent] to file name.

### ISSUE THREAD

**Issue by minhtranite** [facebook/stylex#105]
**Is your feature request related to a problem? Please describe.**
Currently with webpack config like below, a file with the name `styles.css` is created after the build.
<img width="391" alt="image" src="https://github.com/facebook/stylex/assets/5418628/87c9c945-b9a7-4bae-a118-453587f24f73">

**Describe a solution you'd like**
I'm expecting a hashcontent will be added to the file name according to the webpack `output.filename` config to resolve the caching issue.

**Describe alternatives you've considered**
Or can `@stylexjs/webpack-plugin` support add `[hashcontent]` to the `filename` config? like this:

```
new StylexPlugin({
      filename: 'styles.[hashcontent].css',
}),
```

**Comment by nmn** [comment]
This is a known issue and something we've been unable to prioritise so far. Would appreciate a PR for this.

**Comment by pramodgoud7** [comment]
i will work on it

**Comment by Afterdie** [comment]
Since there are no updates, I'd like to work on this.

**Comment by nmn** [comment]
I'm happy to accept whichever PR comes first, so @pramodgoud7 if you've made progress on this, you should let @Afterdie know so one of you doesn't end up wasting your time.

**Comment by minhtranite** [comment]
Hi guys! I pulled the latest code and ran `npm run build -w webpack-example` but it still not working.

<img width="805" alt="image" src="https://github.com/facebook/stylex/assets/5418628/ffbf0825-a195-4f1a-9d54-2330fa6ae0bf">

**Comment by Afterdie** [comment]
Ah.. I was looking at the wrong place for build files my bad.

**Comment by nmn** [comment]
I'll look into it.
