### ISSUE TITLE
Intellisense when defining styles in `create` function

### ISSUE THREAD

**Issue by Niznikr** [facebook/stylex#108]
**Is your feature request related to a problem? Please describe.**
When defining styles for `stylex.create` I'd like TS intellisense for common CSS values for each property, such as `block` for `display`. `stylex.keyframes` seems to support this already.

**Describe a solution you'd like**
For the param type within create instead of ```type UserAuthoredStyles = { [key: string]: unknown };``` set it to ```type UserAuthoredStyles = { [key: string]: CSSProperties };``` (from `@stylexjs/stylex/lib/StyleXCSSTypes`)

**Describe alternatives you've considered**
Right now this seems to work:

```
import type { CSSProperties } from '@stylexjs/stylex/lib/StyleXCSSTypes';
import * as stylex from '@stylexjs/stylex';

const namespaces: Record<string, CSSProperties> = {
    base: {
      display: 'inline-block',
    }
};
const styles = stylex.create(namespaces);
```

**Additional context**

**Comment by Niznikr** [comment]
Resolved by #84

**Comment by necolas** [comment]
@nmn maybe we should use package exports to prevent imports from internals, i.e., only allow imprts from the `@stylexjs/stylex` package?

**Comment by nmn** [comment]
We will need to set up some tooling for this, but it should be simpler to do so for just the Typescript types. Will look into it.
