### ISSUE TITLE
Using imported variables to define styles

### ISSUE THREAD

**Issue by kevintyj** [facebook/stylex#112]
I was wondering if there was any way to get imported values working in StyleX like so:

```ts
// colorTokens.stylex.ts

import { something } from './test'; // const something = '#ffffff'

const testBg = something;

export const DARK_MODE = '@media (prefers-color-scheme: dark)';

export const colorTokens = stylex.defineVars({
	bgColor: {
		default: testBg,
		[DARK_MODE]: testBg,
	},
});

```

I cannot tell If this is a supported pattern. I am currently getting the error `Only static values are allowed inside of a stylex.create() call.`

**Comment by nmn** [comment]
This is not a supported pattern. StyleX is a compiler so all values need to be defined locally. The only exception to this rule is Variables defined with `defineVars` in a `.stylex.js` file.

In the case of variables, we don't actually read the file being imported at all. Instead we rely on the import name, and file path (relative to `rootDir`) to hash and generate variable names.

In your example, it *is* possible to use one variable to define another variable. So if `./test.stylex` was imported, and you exported variables with `defineVars` in that file, that would.

---

You might want to share values across files. There are two patterns to achieve this:

### You can export compiled styles with `stylex.create()` directly

```tsx
// foo.js

export const colorStyles = stylex.create({
  white: {color: '#fff'},
});
```

```tsx
// bar.js
import {colorStyles} from './foo';

const x = stylex.props(
  // ... other styles ...,
  colorStyles.white,
  // ... other styles ...,
);

// OR
const styles = stylex.create({
  container: {
    ...stylex.include(colorStyles.white),
    // ... other styles ...
  },
})
```

### You can use types to enforce consistency

If you want to share the same media queries in various files, you can use a type to enforce that they're all the same.


```tsx
// common-types.ts
export type TDarkMediaQuery = '@media (prefers-color-scheme: dark)';

// Some component file
const DARK_MODE: TDarkMediaQuery = '@media (prefers-color-scheme: dark)';
```

----

# Only `defineVars` are allowed in `.stylex.ts` files.

In your example, you're exporting a media query as value. This doesn't work in general. But also, the only exports allowed in a `.stylex.ts` file are variables defined with `defineVars`.

**Comment by kevintyj** [comment]
This is actually really informative and really helpful! Perhaps this should be a topic that is covered in the docs? I am assuming many are trying to use existing tokens with StyleX.

**Comment by nmn** [comment]
What specifically would you like to see in the docs? We don't want to talk about Shared Media queries yet, because we don't know what it will look like.

**Comment by kevintyj** [comment]
> What specifically would you like to see in the docs? We don't want to talk about Shared Media queries yet, because we don't know what it will look like.

Just did some further testing:
It seems that when importing variables from external libraries, it doesnt work even within `defineVars`. I maintain a personal color library for the colors that I use for my personal projects and some projects at work, would love to directly import and use these colors as variables into a project like so:
```ts
import * as colors from '@me/my-personal-colors'

export const colorTokens = stylex.defineVars({
	bgColor: colors.neutral.0
});
```
But the part about adding to the docs was more on the sharing values across files. But since it is a temporary limitation with a new process of adding additional capabilities when defining vars in on the horizon, perhaps we could wait for the implementation to come. But I think it would also be helpful to document a few purposeful limitations/patterns like the ones you shared above and many others in the issue board.

**Comment by nmn** [comment]
> It seems that when importing variables from external libraries, it doesnt work 

> But since it is a temporary limitation

Let me clarify the rules of compilation:

- Every StyleX function other than `stylex.props()` (and the deprecated `stylex()`) is essentially a macro that is compiled away.
- Therefore, all arguments passed into `stylex.create`, `stylex.defineVars` etc, need to be statically analysable *in the same file*.
- There is *ONE* exception to the no imports rule. Any file can import a named export of `stylex.defineVars` call from a `.stylex.js` file. This exception applies to both `stylex.create`, `stylex.createTheme` and other `stylex.defineVars` calls.

Does that make sense?

**Comment by nmn** [comment]
Yup. Look through `open-props` for an example of how to share styles. I'm working on removing unused CSS variables after generating the CSS bundle. This will just be a Postcss plugin.

**Comment by o-alexandrov** [comment]
@nmn have you tried adding a new concept calling it “special global variables” that get replaced at build time before stylex plugin?

Such global variables would get replaced using replace plugin, for example: [rollup-plugin-replace](https://www.npmjs.com/package/@rollup/plugin-replace).
- every bundler (webpack, esbuild, etc. has a similar plugin)

**Comment by nmn** [comment]
> @nmn have you tried adding a new concept calling it “special global variables” that get replaced at build time before stylex plugin?

I have been thinking along similar lines to create a standalone project to implement something like Bun's macro system in Babel. But this would be a project separate from StyleX itself. You're allowed to use any transformation steps you want *before* StyleX, but StyleX won't handle this for you.

----

Also, the question in this issue seems to have been addressed, so I'm converting this to a discussion.
