### ISSUE TITLE
`Next.js` example app is broken

### ISSUE THREAD

**Issue by nedjulius** [facebook/stylex#118]
**The problem**

The `Next.js` example app is not working due to the `Only static values are allowed inside of a stylex.create() call` error.

**How to reproduce**

Steps to reproduce:
1. Install dependencies of monorepo
2. Navigate to `nextjs-example`
3. Run `npm run build` (or `npm run dev` and the navigate to `https://localhost:{port}`)

**Expected behavior**

The app should not crash due to the `NON_STATIC_VALUE` error. Seems like the token file is following the correct conventions.

**Environment (include versions). Did this work in previous versions?**
- Node version `18.19`
- macOS `Ventura 13.3.1`

It was my first time running this example

**Comment by nmn** [comment]
I'm not able to reproduce this on my mac.

**Comment by nedjulius** [comment]
@nmn alright this fixed the problem lol, perhaps I had some outdated external builds. thanks for quick response and help!

**Comment by nmn** [comment]
There is a design issue because the `reset` styles in `global.css` are overriding StyleX styles. I'm fixing this shortly.
