### ISSUE TITLE
Copy to ClipBoard option not working properly for Installation Command 

### ISSUE THREAD

**Issue by moodyMayank** [facebook/stylex#121]
**The problem**
When I click the option of copy to clipboard for the stylex installation command.
![image](https://github.com/facebook/stylex/assets/100838996/613e8fa6-167c-43c3-b5ff-71339c525141)

- It picks the $ sign also and when I copy it in the terminal, it does not work directly, first I have to remove the $ sign and then the command works.
![image](https://github.com/facebook/stylex/assets/100838996/bae797d8-136c-4507-95a3-a31ff7c38c2c)
- That is the same behavior with other plug-in installations.

**How to reproduce**
Go to the Installation section, click on the copy to Clipboard Option, and then CTRL+V in the terminal and press enter error will come.

**Expected behavior**
The commands should run directly without having to remove the $ manually every time.

**Environment (include versions). Did this work in previous versions?**
Ubuntu Linux

**Comment by purohitdheeraj** [comment]
The `$` sign is likely used for illustrative purposes. Perhaps it can be omitted, as we are utilizing the [CodeBlock](https://docusaurus.io/docs/markdown-features/code-blocks) Component from Docusaurus

**Comment by moodyMayank** [comment]
I would like to work on it , and see what would be the best option and accordingly make the changes

**Comment by nmn** [comment]
It's yours @moodyMayank

**Comment by purohitdheeraj** [comment]
Hey @moodyMayank are you working on it ? or may i add a quick fix for it

**Comment by nelsonuprety1** [comment]
Hello, please check #151 for the fix of this issue. Thank you.
