### ISSUE TITLE
Usage with Server Components and React Native

### ISSUE THREAD

**Issue by rimoslav** [facebook/stylex#123]
Hello,

I have two questions regarding StyleX, and I apologise if this is not the correct way to ask them.

**1st question: StyleX + Server Components**

I couldn't find any detailed information about usage of StyleX in React Server Components.

I've found this [in the docs](https://stylexjs.com/docs/learn/theming/defining-variables/#design-inspiration):

> The design of the theming APIs in StyleX are directly inspired by React's Context APIs. Variables are defined with default values similar to how React Contexts are created, and themes can be created to “provide” different values for these variables for UI sub-trees.

which implies that StyleX might have the same issue as Styled Components when it comes to React Server Components, and that doesn't seem right.

I've found one [Jack Herrington's article](https://jherr2020.medium.com/stylex-metas-solution-to-scalable-css-0e06972d9bc4) that states that the usage is possible, but it doesn't clearly state that all features will work as expected.

I've seen your [NextJS example](https://github.com/facebook/stylex/tree/main/apps/nextjs-example) but that still doesn't fully answer my question.

Will all the StyleX features work without restrictions in all React components?

---

**2nd question: StyleX + React Native**

Same question as before, does it work, what are the constrains etc...

Thanks.

**Comment by nmn** [comment]
> Will all the StyleX features work without restrictions in all React components?

Yes. *All* of StyleX will work with React, Next and React Server Components.

> The design of the theming APIs in StyleX are directly inspired by React's Context APIs. 

This only refers to the API design:
- `createContext` -> `defineVars`
- `context.Provider` -> `createTheme`

We generate static CSS variables, we don't have the same limitations as React Context.

> StyleX + React Native

This does not exist at the moment. We are working on this as a completely separate project.

**Comment by rimoslav** [comment]
Hi @nmn, 

Thanks for the explanation. All clear now, I'll close the issue.

**Comment by akashdevcc** [comment]
Hi @nmn 

> This does not exist at the moment. We are working on this as a completely separate project.

Any timeline on this separate project "to support StyleX for React Native"?
Is there already a public repository for this?

I am starting a new React Native / Expo project, and would like to use StyleX instead of Nativewind.

**Comment by nmn** [comment]
@akashdevcc I don't have a timeline at this moment, but don't expect it anytime soon. It's not a big team, and we're currently focussed on making StyleX for the web stable enough for the vast majority of common use-cases.

**Comment by necolas** [comment]
Our solution for using StyleX on native is now open source: https://github.com/facebook/react-strict-dom

**Comment by akashdevcc** [comment]
@necolas is "react-strict-dom" ready to be used in production react-native/expo apps? And is it already being used internally in Meta by any Meta app?

**Comment by nmn** [comment]
@akashdevcc Please follow the link and read the Readme.md.
