### ISSUE TITLE
Combine styles at `stylex.create()` level

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#136]
**Is your feature request related to a problem? Please describe.**

I would like to be able to combine styles at `stylex.create()` level.

Also, i would like to apply existing styles, with a different pseudo class (ie. define a style, and apply it to another element with :hover pseudo class).

To illustrate my point, let's say I have a shadow style:

```ts
export const shadowStyles = stylex.create({
  base: {
    '::before': { /* ... */ },
    '::after': { /* ... */ },
  },
  level0: {
    '::before': { boxShadow: `0 0 0 0 ${colorScheme.shadow}` },
    '::after': { boxShadow: `0 0 0 0 ${colorScheme.shadow}` },
  },
  level5: {
    '::before': { boxShadow: `0 4px 4px 0 ${colorScheme.shadow}` },
    '::after': { boxShadow: `0 8px 12px 6px ${colorScheme.shadow}` },
  },
});
```

I want it to be applied like this:

```html
<div class="base level0 hover:level5" />
```

**Describe a solution you'd like**

Ideally, I would like to use it like this:

```ts
export const buttonStyles = stylex.create({
  container: {
    className: {
      default: stylex.apply(shadowStyles.base, shadowStyles.level0),
      ':hover': stylex.apply(shadowStyles.level5),
    },
  },
});
```

```tsx
export const Button = ({ children }) => <div {...stylex.props(buttonStyles.container)}>{children}</div>;
```
Does it make sense to you?

**Describe alternatives you've considered**

I don't have any alternative.

**Comment by nmn** [comment]
> I would like to be able to combine styles at stylex.create() level.

This is possible by using and spreading the result of `stylex.include`

> Also, i would like to apply existing styles, with a different pseudo class

This is not possible. You can only spread styles on the top level.

**Comment by olivierpascal** [comment]
> This is possible by using and spreading the result of `stylex.include`.

Thanks, this works well and definitely should be documented ^_^

**Comment by nmn** [comment]
@olivierpascal We haven't documented it for a couple of reasons:

1. We have seen near-zero usage of `stylex.include` internally, so we're not convinced developers will find much use for it.
2. You can only spread it at the top-level of styles. Trying to use it within `::before` will break. This exception makes the API a bit messy in my opinion. I don't like APIs where a bunch of caveats need to be explained.

We're going to leave it undocumented for a while and see how often people ask for or need something like it.

**Comment by HQ92** [comment]
I've also been wondering if stylex.include actually works because I haven't been able to get it to work so far. I can see it being used to encapsulate small groups of css into reusable components essentially that can be used to build more layered style collections inside stylex rather then in components. An example would be as follows:

```js


const commonFrame = stylex.create({
  base: {
    height: `100%`,
    width: `100%`,
    paddingTop: `0`,
    paddingBottom: `0`,
    paddingLeft: `30px`,
    paddingRight: `30px`,
    position: 'relative',
    margin: 'auto',
    minHeight: `100px`,
    display: 'block',
  },
});
const frame = stylex.create({
  content: {
    ...stylex.include(commonFrame.base),
    paddingLeft: {
      // eslint-disable-next-line @stylexjs/valid-styles
      [greaterThanIncSmallDesktop]: `210px`,
    },
    paddingRight: {
      // eslint-disable-next-line @stylexjs/valid-styles
      [greaterThanIncSmallDesktop]: `210px`,
    },
  },
});
const flex = stylex.create({
  container: {
    display: 'flex',
    minHeight: 0,
    minWidth: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
});
const s = stylex.create({
  wrapper: {
    ...stylex.include(frame.content),
    ...stylex.include(flex.container),
    height: 'auto',
    width: '100%',
    flexFlow: 'column',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    backgroundColor: '#060908',
    gap: `50px`,
    paddingTop: `100px`,
    paddingBottom: `100px`,
  },
});

export const El = () => (
    <div {...stylex.props(s.wrapper)}>item</div>
)

```

At the moment the above does not seem to work, it only works if applying the separate stylex classnames directly to the component itself:

```js

export const El = () => (
    <div {...stylex.props(commonFrame.base, frame.content, flex.container, s.wrapper)}>item</div>
)

````

**Comment by nmn** [comment]
I'm investigating why `stylex.include` is not working for you.

However, I do see a couple of issues:

```tsx
content: {
  ...stylex.include(commonFrame.base),
  paddingInline: {
    default: 30
    [greaterThanIncSmallDesktop]: 210,
  },
},
```

You can't override *just* for a media query. If you override `paddingLeft` you have to override all of it. (I combined `paddingLeft` and `paddingRight` into `paddingInline` for you)

**Comment by HQ92** [comment]
> I'm investigating why `stylex.include` is not working for you.
> 
> However, I do see a couple of issues:
> 
> ```tsx
> content: {
>   ...stylex.include(commonFrame.base),
>   paddingInline: {
>     default: 30
>     [greaterThanIncSmallDesktop]: 210,
>   },
> },
> ```
> 
> You can't override _just_ for a media query. If you override `paddingLeft` you have to override all of it. (I combined `paddingLeft` and `paddingRight` into `paddingInline` for you)

Was there a reason for not allowing overrides just for a media query? I'm thinking of situations where you might want a base space for mobile devices, and then larger ones for different sections on desktop where you wouldn't want to necessarily duplicate default values where they could just be built up?

**Comment by nmn** [comment]
> Was there a reason for not allowing overrides just for a media query?

Yes. A lot of thought has gone into this. I'll try to summarise:
1. It's a design philosophy: You shouldn't think about "mobile" styles vs "desktop" styles. You have styles and some of them adapt to screen size. This incentives fluid design and reduces over-reliance on media queries and reduces the total amount of CSS needed.
2. Consistent merging of styles. If you pass a style with `margin:0` to a component, you want the margin to be `0`. You don't want to go check the source for all the media queries it might be using etc. The current model makes this reliable.
3. Future RN compatibility. Without getting too in the weeds, RN doesn't natively support Media queries, and doesn't have the same specificity design. The current design is compatible, separate media queries would break.

**Comment by salvadorplj** [comment]
@nmn any chance includes becomes official and documented? Being able to use it becomes essential to crating a wide-scale design system; creating styles that inherit others' is a basic OOP feature to keep everything sane and make Stylex really usable.

**Comment by salvadorplj** [comment]
> Use the array syntax to combine styles. There is no functional difference from `includes`. We've explained this many times over
@necolas Thanks for your response, can you point me on the right direction where I can find these explanations? I've tried and could not find anything

**Comment by necolas** [comment]
https://stylexjs.com/docs/learn/styling-ui/using-styles/#merging-styles

**Comment by piotrblasiak** [comment]
I agree that include should be documented. The reason is that the documented merging using stylex.props is done directly on the element, which conflicts with cleanly defining the styles of that element in the top of the file in stylex.create. For example:

```
const styles = stylex.create({
  label: {
    color: "red",
  },
});

<div>
  <div {...stylex.props(commonStyles.title, styles.label)}></div>
</div>
```

Looking at this code, one thinks that all styles are in styles, but no - you also need to know that commonStyles.title is merged, which you only can by looking at the spread.

**Comment by nmn** [comment]
`stylex.include` has unresolved issues and it is not a priority so I would not recommend using it at all.

**Comment by zaydek** [comment]
> I agree that include should be documented. The reason is that the documented merging using stylex.props is done directly on the element, which conflicts with cleanly defining the styles of that element in the top of the file in stylex.create. For example:
> 
> ```tsx
> const styles = stylex.create({
>   label: {
>     color: "red",
>   },
> });
> 
> <div>
>   <div {...stylex.props(commonStyles.title, styles.label)}></div>
> </div>
> ```
> 
> Looking at this code, one thinks that all styles are in styles, but no - you also need to know that commonStyles.title is merged, which you only can by looking at the spread.


It's worth mentioning there are actually some valid reasons not to use `stylex.include`. I used to want to use it to model "perfect" classes, but it throws TypeScript through a loop because now you are specifying redundant properties on the same object, which is pretty annoying.

<img width="151" alt="Screenshot 2025-01-10 at 9 13 50 PM" src="https://github.com/user-attachments/assets/4f64369e-4541-41ac-b9ee-453a793cd5bd" />

```
'foo' is specified more than once, so this usage will be overwritten.ts(2783)
```

This comes up with `stylex.include` too. So given that, and the fact it's not officially recommended/endorsed, what I do when I want to compose multiple disparate styles is simply create a component so I don't have to worry about the internals from the outside looking in.

`<input>` is a good example of this because they are void elements that are generally expected to take on the esthetic of some kind of typography system. So I export a `typography` style object and call into it. Then I consume the component, not the styles.

```tsx
export type InputProps = Sx.DOMComponentProps<"input", void>;
export function Input(props: InputProps): React.JSX.Element {
  return (
    <VoidFocusRing borderRadius={Spacing.Md}>
      <input
        {...props.DOMProps}
        {...stylex.props(
          // Inherit typography styles
          typography.paragraph,

          styles.input,
          props.styles,
        )}
      />
    </VoidFocusRing>
  );
}
```

Slightly annoying? Sure. But the TS warnings are more annoying and components obfuscate all the internals anyway.

**Comment by zaydek** [comment]
I guess I should mention that technically this is how to make TS happy:

```tsx
const bar = {
  foo: "hello",
}

const foo = {
  ...bar,
  foo: "hello",
}
```

But it also means that you have to specify `stylex.include` first as opposed to last which may not be intuitive. In my mind I'm tacking a style onto another one. At least with `stylex.props` I can control whether the placement of `typography.paragraph` without worrying about upsetting TS. Small things but maybe makes you feel more comfortable just using `stylex.props`. :)
