### ISSUE TITLE
Target '.class[pseudo class] [pseudo element]', ie. '.button:hover ::before', or ':before:hover:prop' in tw

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#137]
**Is your feature request related to a problem? Please describe.**

I would like to target `.class[pseudo class] [pseudo element]`, ie. `.button:hover ::before`.

**Describe a solution you'd like**

```ts
const buttonStyles = stylex.create({
  shadow: {
    boxShadow: {
      default: null,
      ':hover': {
        '::before': `0 4px 4px 0 ${colorScheme.shadow}`,
        '::after': `0 8px 12px 6px ${colorScheme.shadow}`,
      },
    },
  },
});
```

**Describe alternatives you've considered**

I have no alternative yet.

**Comment by necolas** [comment]
Did you mean `.button:hover::before`?

**Comment by nmn** [comment]
What you are asking for is essentially a descendent selector. We have documented that this is not supported for now.

https://stylexjs.com/docs/learn/thinking-in-stylex/#encapsulation

The current workaround for such situations is to set the value of a variable in the parent and read it in the child.

```ts
import {myVars} from './variables.stylex';

const buttonStyles = stylex.create({
  shadow: {
    [myVars.shadowStart]: {
      default: null,
      ':hover': `0 4px 4px 0 ${colorScheme.shadow}`,
    },
  },
  child: {
    boxShadow: myVars.shadowStart,
  }
});
```

**Comment by olivierpascal** [comment]
That's genius. Thanks.

**Comment by olivierpascal** [comment]
@nmn  Hum after all I think I don't fully get how your workaround works.

How does `myVars.shadowStart` is set in your code?
Does `[myVars.shadowStart]: { ... }` can really set a var content?

I get `eslint: Computed key cannot be resolved` when I am using your syntax.

Also, can `stylex.create` be used to set an arbitrary var like `--my-var: 'my-content';`? I get `eslint: This is not a key that is allowed by stylex` when trying to do so.

Thanks.

**Comment by nmn** [comment]
> Does [myVars.shadowStart]: { ... } can really set a var content?

Yes! StyleX can use variables in both the key and var position. This approach is meant for one-offs, as opposed to `createTheme` which is meant to override a bunch of variables together.

> I get eslint: Computed key cannot be resolved when I am using your syntax.

This is bug in the ESLint plugin. I tried to fix it just before release, but it needs some more work.

> ...can stylex.create be used to set an arbitrary var like --my-var: 'my-content';?

This is not an officially supported pattern because you're using a non-StyleX variable, but it does work.

**Comment by olivierpascal** [comment]
Ok thanks. After all it's seems very hacky to me, and too complicated for my usecase. I end up using JS events `onPointerEnter` / `onPointerLeave` and a React state variable. Still hacky, not perfect but cleaner imho.

**Comment by nmn** [comment]
We know the approach we can take, but still discussing the API. Will share an RFC soon.

**Comment by olivierpascal** [comment]
> What you are asking for is essentially a descendent selector. We have documented that this is not supported for now.

Will you also support ascendent selectors?

> The current workaround for such situations is to set the value of a variable in the parent and read it in the child.

Do you by any chance have a workaround to address this?

```html
<!-- the div container has to be red when the button is hover -->
<div class="container">
  <button>Button</Button>
</div>
```

**Comment by olivierpascal** [comment]
Here is my workaround:

```ts
const styles = stylex.create({
 container: {
    backgroundColor: {
      default: 'inherit',
      ':has(button:hover)': 'red',
    },
  }
});
```

NOTE: as @nmn mentioned, ["this is a workaround and may stop working sometime in the future."](https://github.com/facebook/stylex/discussions/224#discussioncomment-7913922).

**Comment by nmn** [comment]
@olivierpascal That workaround is fine and doesn't break encapsulation. (There is no styling at a distance, only observing). The official API will generate the same thing eventually. So yes, we're looking at selectors in all 4 directions.

**Comment by necolas** [comment]
It is unlikely, however, that any of these select types will be supported in React Native - especially when it requires knowledge of the underlying element type that might be encapsulated within a composite component

**Comment by nmn** [comment]
Yes, to be clear, no complex selectors will be supported in React Native at all. In any of the four directions.

**Comment by necolas** [comment]
Arguably anything like this - `':has(button:hover)'` - shouldn't be allowed on web either, as part of the selector is an element type - and there could be many or no `button` elements in the subtree. Inevitably people will want to scope this to a *specific* button when it goes bad, and will probably reach for a more specific selector type like an attribute selector. Not to mention that `:hover`-related styling has general drawbacks for touch device UX. Ignoring my skepticism about this pattern being a good UX, the most reliable mechanism is probably to use JS callbacks.

**Comment by asaf** [comment]
Is there a workaround for sibling selector such: `.mycheckbox:checked + .label span`

In a case such:

```html
<input
  type="checkbox"
/>
<label>
  <span>content</span>
</label>
```

I'd like to change the span property based on the 'checked' state of the input.

thanks.

**Comment by nmn** [comment]
Using the "checkbox hack` is considered bad for accessibility anyway.

I'd suggest using JS to do this and also set the correct aria-attributes accordingly.

**Comment by nikeee** [comment]
> What you are asking for is essentially a descendent selector. We have documented that this is not supported for now.
> 
> [stylexjs.com/docs/learn/thinking-in-stylex#encapsulation](https://stylexjs.com/docs/learn/thinking-in-stylex/#encapsulation)
> 
> The current workaround for such situations is to set the value of a variable in the parent and read it in the child.

I'm currently trying to style an `input[type=range]` and I think I'm facing a similar problem. Consider this code that styles the slider's thumb based on the hover of the input: 
```scss
.slider {
    &::-webkit-slider-thumb {
        background-color: red;
    }
    &:hover::-webkit-slider-thumb {
        background-color: green;
    }
}
```

If I understand the variable use correctly, this would be the workaround:
```ts
const someVars stylex.defineVars({
    thumbHover: "unset",
});

const slider = stylex.create({
    slider: {
        [someVars.thumbHover]: {
            default: "red",
            ":hover": "green",
        },

        "::-webkit-slider-thumb": {
            backgroundColor: someVars.thumbHover
        },
    },
});
```

Is this approach correct? If so, does it resemble the current best practice?

**Comment by nmn** [comment]
@nikeee Yes, this is currently the recommended best practice. 

The one important thing to note is that you must follow [the rules when defining variables](https://stylexjs.com/docs/learn/theming/defining-variables/#rules-when-defining-variables) when using `stylex.defineVars`. i.e., `stylex.defineVars` must be in a separate file and the file name must have a `.stylex.ts` extension.

Making this change will also fix the lint error that you're seein.

---

```tsx
// tokens.stylex.ts
export const someVars stylex.defineVars({
    thumbHover: "unset",
});
```

```tsx
// somefile.tsx
import {someVars} from './tokens.stylex.ts';

const slider = stylex.create({
    slider: {
        [someVars.thumbHover]: {
            default: "red",
            ":hover": "green",
        },

        "::-webkit-slider-thumb": {
            backgroundColor: someVars.thumbHover
        },
    },
});
```
