### ISSUE TITLE
Choose cascade layer usage in bundler plugins

### ISSUE THREAD

**Issue by kotarella1110** [facebook/stylex#138]
**Is your feature request related to a problem? Please describe.**

Currently, only when using the Rollup plugin, the definition of style order of precedence on the [cascade layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer). However, in the plugins for Webpack and Next.js, the cascade layer polyfill (`:not(#\#)`) is utilized. Is this intentional? From the perspective of CSS size, there may be cases where one would prefer to use the cascade layer without the polyfill.

**Describe a solution you'd like**

It would be beneficial if users could choose whether or not to use the cascade layer.

**Describe alternatives you've considered**

Consider adding a `useLayer` option as follows, allowing users to choose whether to use the cascade layer or the cascade layer polyfill:

Rollup:

```diff
import stylexPlugin from '@stylexjs/rollup-plugin';

stylexPlugin({
  fileName: 'stylex.css'
+ useLayer: true,
})
```

Webpack:

```diff
const StylexPlugin = require('@stylexjs/webpack-plugin');

new StylexPlugin({
  filename: 'styles.css',
+ useLayer: true,
})
```

Next.js:

```diff
const stylexPlugin = require('@stylexjs/nextjs-plugin');

module.exports = stylexPlugin({
  rootDir: __dirname,
+ useLayer: true,
})({});
```

**Additional context**

If this proposal is accepted, I am willing to create a pull request.

**Comment by kotarella1110** [comment]
Sorry. I was reading old code. I will close the PR adding the option as it seems to have been merged.
https://github.com/facebook/stylex/pull/100/files

**Comment by nmn** [comment]
> From the perspective of CSS size, there may be cases where one would prefer to use the cascade layer without the polyfill.

CSS size is not of concern here, since the `:not(#\#)` pattern is highly repetitive and gzips well.
