### ISSUE TITLE
Be able to provide an extra class to stylex.props()

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#155]
**Is your feature request related to a problem? Please describe.**

I need to assign my container an extra class, let's say 'my-custom-class'.

**Describe a solution you'd like**

```ts
<div {...stylex.props(styles.container, 'my-custom-class')} />
```

To be compiled to:

```html
<div class="x1vqgdyp my-custom-class" />
```

Of course, I cannot do:

```ts
<div {...stylex.props(styles.container)} className='my-custom-class' />
```

**Describe alternatives you've considered**

No one.

**Comment by nmn** [comment]
This is a known issue and under consideration. Thanks for creating a task for it. Here's the current workaround to unblock you:

```tsx

const customClassName: any = {my-custom-class: 'my-custom-class', $$css: true};

<div {...stylex.props(styles.container, customClassName)} />
```

---

## Why this feature isn't officially supported

We don't want people trying to apply non-stylex classes and stylex classes on the same element as it breaks all StyleX guarantees and leads to unpredictable results. Also, using class names for anything other than styles is usually an anti-pattern and you should be using `data-id` or some other attribute.

Would you explain your use-case?

**Comment by nmn** [comment]
Please use the workaround I suggested for now. I'm discussing the best approach to solve this.

**Comment by olivierpascal** [comment]
Thank you. Could you please point me to the correct type for `customClassName` that will be accepted by `stylex.props()`?

**Comment by nmn** [comment]
```ts
const customClassName: any = {'my-custom-class': 'my-custom-class', $$css: true};
```

Use the same string as the key and value.

**Comment by necolas** [comment]
This is strongly discouraged though. It's exposing and using an implementation detail of the runtime. StyleX is not meant to style elements that are also using another CSS library.

**Comment by nmn** [comment]
> It's exposing and using an implementation detail of the runtime.

Yes. @olivierpascal this pattern can break at any point in the future, so beware. Closing the issue.
