### ISSUE TITLE
Typo on the eslint-plugin API reference page

### ISSUE THREAD

**Issue by charu1603** [facebook/stylex#159]
**The problem**
I encountered a syntax error on the page where three dots are left. 

![Screenshot (520)](https://github.com/facebook/stylex/assets/96014425/d16a7c2c-acfb-426b-9ddb-8b18433b261c)

I can solve this issue. Please assign it to me.

**Comment by nmn** [comment]
All yours!

**Comment by aayushchugh** [comment]
shouldn't this issue be closed?
