### ISSUE TITLE
docs: Missing readme docs for `@stylexjs/nextjs-plugin`

### ISSUE THREAD

**Issue by aayushchugh** [facebook/stylex#164]
The `README` file for `@stylexjs/nextjs-plugin` only contains `...` and is missing the actual docs

Assign the issue to me and I can take reference from actual [docs](https://stylexjs.com/docs/learn/installation/) and write it into readme 

<img width="808" alt="image" src="https://github.com/facebook/stylex/assets/69336518/9b92ea74-31a9-4f41-98f7-bc090d86a794">
<img width="626" alt="image" src="https://github.com/facebook/stylex/assets/69336518/57434649-b6cd-405e-b299-18cfa3ca09fb">

## edit:
docs for `@stylexjs/rollup-plugin` and `@stylexjs/webpack-plugin` are also missing

**Comment by joshuabaker** [comment]
There’s an [example app](https://github.com/facebook/stylex/tree/f78c96f504fcc2989d074cc0643ec78ec1ebb579/apps/nextjs-example) that helped get me up and running.

Here’s my `next.config.js` for reference.

```js
const styleXPlugin = require("@stylexjs/nextjs-plugin");

/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = styleXPlugin({
  rootDir: __dirname,
})(nextConfig);
```

You also need to add a `.babelrc.js` file.

```js
module.exports = {
  presets: ["next/babel"],
  plugins: [
    [
      "@stylexjs/babel-plugin",
      {
        dev: process.env.NODE_ENV === "development",
        runtimeInjection: false,
        genConditionalClasses: true,
        treeshakeCompensation: true,
        unstable_moduleResolution: {
          type: "commonJS",
          rootDir: __dirname,
        },
      },
    ],
  ],
};
```

**Comment by aayushchugh** [comment]
yeah docs are provided on the website but not in the readme

**Comment by nmn** [comment]
Assigned.

**Comment by hustlerZzZ** [comment]
I am creating issue for empty readme for @stylexjs/rollup-plugin but then I saw this issue is already created.
Can I fix the rollup-plugin readme file.

If yes, can you please assign this to me @nmn

**Comment by aayushchugh** [comment]
> I am creating issue for empty readme for @stylexjs/rollup-plugin but then I saw this issue is already created.
> 
> Can I fix the rollup-plugin readme file.
> 
> 
> 
> If yes, can you please assign this to me @nmn 
> 
> 

I will be working on this one 😊

**Comment by hustlerZzZ** [comment]
> > I am creating issue for empty readme for @stylexjs/rollup-plugin but then I saw this issue is already created.
> > 
> > Can I fix the rollup-plugin readme file.
> > 
> > 
> > 
> > If yes, can you please assign this to me @nmn 
> > 
> > 
> 
> I am working on this one 😊

I think it will be speedy if we split the work.

**Comment by aayushchugh** [comment]
@hustlerZzZ okay, you can work on rolup one and I will work on nextjs one.

**Comment by aayushchugh** [comment]
@hustlerZzZ I have created a PR you can co-author it if you like or you can create your own

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ I have created a PR you can co-author it if you like or you can create your own

Ok sure
