### ISSUE TITLE
OverridesForTokenType is too restrictive

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#176]
**The problem**

OverridesForTokenType may be too restrictive: 

**How to reproduce**

```ts
// vars.stylex.ts

import * as stylex from '@stylexjs/stylex';
import { colorScheme } from './colorScheme.stylex';

export const vars = stylex.defineVars({
  containerColor: colorScheme.primary
});
```

```ts
// themedVars.ts

import * as stylex from '@stylexjs/stylex';
import { vars } from './vars.stylex';

export const themedVars = stylex.createTheme(componentVars, {
   containerColor: 'none',
// ^^^^^^^^^^^^^^ ts(2345) error here
});
```

```
Types of property 'containerColor' are incompatible.
    Type 'string' is not assignable to type 'StyleXVar<StyleXVar<string>> | { [atRule: `@${string}`]: StyleXVar<StyleXVar<string>>; default: StyleXVar<StyleXVar<string>>; }
```

**Expected behavior**

No error.

Is this behavior expected?

**Comment by nmn** [comment]
This is a bug in the type definitions. Thanks for catching it.

**Comment by develop084** [comment]
is this issue is still there would you please mention the file path for it

**Comment by nmn** [comment]
@develop084 This issue will need to be fixed twice in the `StyleXTypes.js` and `StyleXTypes.d.ts` files.

**Comment by develop084** [comment]
Hi @nmn  I have completed this bug let me know the steps to merge it

**Comment by nmn** [comment]
@develop084 Did you publish a pull request? Please consult the Contributing.md file and Github's normal PR process.

**Comment by develop084** [comment]
@nmn  thanks for a propt reply, I am on it creating a PR with mentioning details
