### ISSUE TITLE
Syntax sugar for writing stylex styles.

### ISSUE THREAD

**Issue by aspizu** [facebook/stylex#178]
Provide a pre-processor which transforms styles written in an CSS-like syntax into Javascript code.

#### Example:

```tsx
const styles = <stylex>
  base {
    fontSize: 16;
    lineHeight: 1.5;
    color: rgba(60, 60, 60);
  }

  highlighted {
    color: rebeccapurple;
  }
</stylex>
```

```ts
const styles = stylex.create({
  base: {
    fontSize: 16,
    lineHeight: 1.5,
    color: "rgb(60, 60, 60)",
  },
  highlighted: {
    color: "rebeccapurple",
  },
});
```

**Comment by nmn** [comment]
This is out of scope. Saving a few keystrokes of typing is a non-goal for StyleX, but Type-safety is. A DSL like this is hardly more convenient and removes type-safety entirely.

Object syntax has been chosen intentionally for enabling type-safety.

Such DSLs can be created by the community. Probably as editor plugins. Like Emmet for HTML, there can be an easy way to type shorthand that expands into StyleX.
