### ISSUE TITLE
"All variables in a variable group must be overridden when creating a theme."

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#188]
**Is your feature request related to a problem? Please describe.**

> All variables in a variable group must be overridden when creating a theme. This choice has been to help catch accidental omissions. Even at the cost of occasional tedium.

Could we discuss this?

When I have a large group of vars to define a theme (ie. a color palette) and I want to create a variant with just a different background color, it's not only 'tedious' to have to override all vars, but also it's not future proof (if some vars in the original group change), and it also generates a lot of duplicates in the compiled code.

(besides, is it possible to clean all unused vars in the compiled css?)

**Describe alternatives you've considered**

```ts
// vars.stylex.ts

import * as stylex from '@stylexjs/stylex';

export const baseVars = {
  // ...
};

export const baseStylexVars = stylex.defineVars(baseVars);
```

```ts
// theme.ts

import * as stylex from '@stylexjs/stylex';
import { baseVars, baseStylexVars } from './vars.stylex';

export const vars = {
  ...baseVars,
  backgroundColor: 'green',
};

export const stylexTheme = stylex.createTheme(baseStylexVars, vars);
```

**Describe a solution you'd like**

To leave the responsability to the developer if all vars should be overridden or not.

Maybe an optional template type could be provided to stylex.createTheme() to ensure the correct type is provided (ie. `stylex.createTheme<Partial<MyVars>>(baseVars, themedVars)`).

What do you think?

**Comment by nmn** [comment]
This design decision is already being hotly debated and there is a trade-off between explicit safety vs convenience.

**Comment by olivierpascal** [comment]
I see. 'safety' does not apply to me for my usecase (also I cannot see one where * all * of the vars would * have * to be overriden) so I guess I'll have to go on with another ugly workaround ^_^'

```ts
// theme.ts

import * as stylex from '@stylexjs/stylex';
import { baseVars, baseStylexVars } from './vars.stylex';

export const vars: Partial<typeof baseVars> = {
  backgroundColor: 'green',
};

export const stylexTheme = stylex.createTheme(baseStylexVars, vars as typeof baseVars);
```

**Comment by nmn** [comment]
@olivierpascal We will be changing the types to allow overriding a subset of variables in the next release. 

Creative workaround BTW!
