### ISSUE TITLE
The ssr option in 'next/dynamic' causes an error.

### ISSUE THREAD

**Issue by codenyang** [facebook/stylex#192]
Steps to reproduce:
1. `const SampleComponent = dynamic( () => import('../components/Sample'));` <- working
2. `const SampleComponent = dynamic( () => import('../components/Sample'), { ssr : true});` <- working
3. `const SampleComponent = dynamic( () => import('../components/Sample'), { ssr : false });` <- error

```sh
Unhandled Runtime Error
Error: Unsupported Server Component type: Null
```

Is there a way to modify it to work?

**Comment by nmn** [comment]
Could you provide more context? 

- Is this for development or production build? 
- Does everything work when not using `next/dynamic`?
- What does `Sample` look like in this example?

**Comment by codenyang** [comment]
It can be reproduced simply by adding the Dynamic option to the 'playground' project code.
You can check below at the URL.

https://stackblitz.com/edit/stylex-next-cvfea9?file=app%2Fpage.tsx

**Comment by nmn** [comment]
This is not a StyleX error. It's a detail of React server components in Next.JS. Setting `ssr` to `false` forces the component to not server rendered. However, you're trying to render a server component.

Either, keep `ssr: true` or put a `"use client"` at the top of the file to make the component where you're using `next/dynamic` a client component as well.

**Comment by codenyang** [comment]
Are you saying that I can't use it even if I add the loading element?
If add a loading element
It seems to be accessible normally in 'app router' that do not use 'stylesxjs'.
However, applying 'stylesxjs' causes an error.

**Comment by nmn** [comment]
> Are you saying that I can't use it even if I add the loading element?

Correct.

> It seems to be accessible normally in 'app router' that do not use 'stylesxjs'.

I verified that this is not the case. Any component rendered on the server side needs to have `ssr` enabled.

**Comment by codenyang** [comment]
I understand.
I checked the behavior after modifying the code. Thank you!
