### ISSUE TITLE
[NextJS] How to apply app wide custom font

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#196]
I'm seeking guidance on applying a font across my entire app.

Currently, I've defined the app font in my globalTokens.stylex.js file using the following code:
```javascript

export const fonts = stylex.defineVars({
    appFont: 'Plus Jakarta Sans',
});

```

Then in my LogInComponent.js file it was referenced as follows:
```javascript

const styles = stylex.create({
    title: {
        color: colors.primaryText,
        fontFamily: fonts.appFont, //Not working
        fontWeight: 600,
        fontSize: text.spanXs
    }
});

```
However, it seems that the specified font is not taking effect. I suspect this may be due to the need to download the font from a URL. Could anyone kindly provide guidance on where and how to make provisions for downloading and integrating this font into the project?

Thank you

**Comment by nmn** [comment]
Try this:

```ts
export const fonts = stylex.defineVars({
    appFont: '"Plus Jakarta Sans"',
});
``

And you'd also need to make sure that you've downloaded the font from a URL.

**Comment by ebitogu** [comment]
@nmn  Thanks for your response. So, this is currently the content of my global.css file:
```css

@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800&display=swap');
@layer reset {
    * {
      box-sizing: border-box;
      padding: 0;
      margin: 0;
    }
}
```

Then in my globalTokens.stylex.js file I have this:
```javascript

export const fonts = stylex.defineVars({
    appFont: '"Plus Jakarta Sans"',
});

```

Now, I tried applying the font to the whole of my application using the following code:

``` javascript
...
import '../globals.css'

const styles = stylex.create({
  html: {
    colorScheme: 'light dark',
  },
  reset: {
    minHeight: '100%',
    margin: 0,
    padding: 0,
  },
  body: {
    background: colors.background,
    fontFamily: fonts.appFont   //Attempt to apply font to the entire app. Not working
  },
});

export default async function RootLayout({ children, params: { locale } }) {

  return (
    <html {...stylex.props(styles.html, styles.reset)} lang={locale}>
      <body {...stylex.props(styles.reset, styles.body)}>{children}</body>
    </html>
  )
}


```

Unfortunately, the font is not taking effect at all. Is there another way out of this?

Thank you for response in anticipation.

**Comment by nmn** [comment]
@ebitogu I just tried to reproduce the issue and it worked fine for me. Here's a stackblitz link where I tried it: https://stackblitz.com/edit/stylex-next-untd91?file=app%2Flayout.tsx

However, there are a few pitfalls that may have caused an issue for you:
1. Is your `global.css` file included in your bundle? Can you use the custom font as a style value directly? (without using a variable)
2. Does adding `import '../globalTokens.stylex';` above the other import fix the problem?
3. Does stopping `npm run dev` and running it again fix the problem?

**Comment by ebitogu** [comment]
@nmn Yes, it's working fine now all of a sudden with no changes made. It seems the stylex plugin didn't parse it after I restarted the server. Weird.

But I will close this now as it's working now. Thank you.

**Comment by nmn** [comment]
@ebitogu There are some issues in dev mode and variables with StyleX. Restart the dev server whenever you run into such issues for now.
