### ISSUE TITLE
StyleX Webpack Plugin 

### ISSUE THREAD

**Issue by 19Qingfeng** [facebook/stylex#197]
**The problem**

I tried using StylexPlugin combined with HtmlWebpackPlugin to showcase my page.

The generated Css file is not associated with the html. I'm not sure if I still need to use StylexPlugin after using @stylexjs/babel-plugin.

I just want to have css link injection of stylex output in the output HTML as well, But there is no such thing now.

I looked up @stylexjs/webpack-plugin's code, Maybe you can try to associate HTMLwebpackPlugin's beforeEmit hook here?

<img width="690" alt="image" src="https://github.com/facebook/stylex/assets/31119562/6f5d83f7-afb6-4e4c-9e00-4b4a95e4dfac">

To be honest, I have not carefully studied the internal mechanism of @stylexjs/webpack-plugin, and I am not sure whether the compiled .tsx file will retain the introduction of css, At least as a result, the import of css is not retained in .tsx, so that output html cannot introduce stylex'css file into the template.

**How to reproduce**

This is a simple example:

[project.zip](https://github.com/facebook/stylex/files/13692411/project.zip)

Steps to reproduce:
1. run `pnpm install`.
2. run `npm run dev` or `npx webpack`.
3. dist/index.html  - No style file injection.

**Expected behavior**

I  hope to be able to inject style files.

**Comment by nmn** [comment]
This is a known limitation. Would love contributions to solve this problem.

**Comment by purohitdheeraj** [comment]
hi @19Qingfeng for a quick workaround we can use template with  HtmlWebpackPlugin 
 tried with your webpack config , able to get the styles

```js

const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const StylexPlugin = require("@stylexjs/webpack-plugin");

module.exports = (env, argv) => ({
	mode: "development",
	entry: {
		app: "./src/main.tsx",
	},
	resolve: {
		extensions: [".js", ".tsx", ".json", ".wasm"],
	},
	module: {
		rules: [
			{
				test: /\.(js|jsx|tsx?)$/,
				exclude: /(node_modules)/,
				use: {
					loader: "babel-loader",
				},
			},
		],
	},
	devServer: {
		port: 9000,
		compress: false,
	},
	output: {
		filename: "js/bundle.js",
		path: path.resolve(__dirname, "./dist"),
	},
	plugins: [
		new StylexPlugin({
			filename: "styles.css",
			dev: argv.mode === "development",
			runtimeInjection: false,
			classNamePrefix: "x",
			unstable_moduleResolution: {
				type: "commonJS",
				rootDir: __dirname,
			},
		}),
		new HtmlWebpackPlugin({
			templateContent: `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>Your Webpack App</title>
          <link rel="stylesheet" href="./styles.css">
        </head>
        <body>
          <div id="root"></div>
        </body>
        </html>
      `,
			filename: "index.html",
			inject: "body",
			chunks: ["app"],
			minify: {
				removeComments: true,
			},
		}),
	],
});
```

**Comment by nedjulius** [comment]
hey, I can give this a shot if nobody's currently working on it

**Comment by 19Qingfeng** [comment]
> hey, I can give this a shot if nobody's currently working on it

I don't think it's a troublesome problem. Maybe we can build it together.

**Comment by 19Qingfeng** [comment]
> hi @19Qingfeng for a quick workaround we can use template with HtmlWebpackPlugin tried with your webpack config , able to get the styles for the build step
> 
> ```js
> const path = require("path");
> const HtmlWebpackPlugin = require("html-webpack-plugin");
> const StylexPlugin = require("@stylexjs/webpack-plugin");
> 
> module.exports = (env, argv) => ({
> 	mode: "development",
> 	entry: {
> 		app: "./src/main.tsx",
> 	},
> 	resolve: {
> 		extensions: [".js", ".tsx", ".json", ".wasm"],
> 	},
> 	module: {
> 		rules: [
> 			{
> 				test: /\.(js|jsx|tsx?)$/,
> 				exclude: /(node_modules)/,
> 				use: {
> 					loader: "babel-loader",
> 				},
> 			},
> 		],
> 	},
> 	devServer: {
> 		port: 9000,
> 		compress: false,
> 	},
> 	output: {
> 		filename: "js/bundle.js",
> 		path: path.resolve(__dirname, "./dist"),
> 	},
> 	plugins: [
> 		new StylexPlugin({
> 			filename: "styles.css",
> 			dev: argv.mode === "development",
> 			runtimeInjection: false,
> 			classNamePrefix: "x",
> 			unstable_moduleResolution: {
> 				type: "commonJS",
> 				rootDir: __dirname,
> 			},
> 		}),
> 		new HtmlWebpackPlugin({
> 			templateContent: `
>         <!DOCTYPE html>
>         <html lang="en">
>         <head>
>           <meta charset="utf-8">
>           <meta name="viewport" content="width=device-width, initial-scale=1">
>           <title>Your Webpack App</title>
>           <link rel="stylesheet" href="./styles.css">
>         </head>
>         <body>
>           <div id="root"></div>
>         </body>
>         </html>
>       `,
> 			filename: "index.html",
> 			inject: "body",
> 			chunks: ["app"],
> 			minify: {
> 				removeComments: true,
> 			},
> 		}),
> 	],
> });
> ```

In fact, there will be a lot of restrictions, just to meet the scenarios in the development environment,I think I will co-build this issue later.
Even so, thank you very much.

**Comment by minhtranite** [comment]
Hi @nedjulius, @nmn. I'm working on this [PR](https://github.com/facebook/stylex/pull/203). It can help resolve this problem, can you take a look? I'm not have much experimence about write webpack plugin so not sure if there is any potential issues!

**Comment by nmn** [comment]
Glad to see the community making progress on this. @minhtranite It will probably take some time to get a review of your PR as I'm not particularly well versed with webpack either, which is why the current plugin has the limitations that you see.

**Comment by andrejcesen** [comment]
I noticed that Next.js plugin appends the generated CSS to the `globals.css` file. It does so by using the `appendTo` param, which is [also available in the webpack plugin](https://github.com/facebook/stylex/blob/main/packages/webpack-plugin/src/index.js#L50). Using this works great in combination with `MiniCssExtractPlugin`.

**Comment by nmn** [comment]
Closing this in favour of #297
