### ISSUE TITLE
Better errors to say that Dynamic Style functions don't support default values

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#198]
Is there a limitation to the kind of arguments that can be passed as arguments to dynamic styles?

I keep getting the following error in the code below:

Error message:
`
common/components/ui/Flex/index.js: Only static values are allowed inside of a stylex.create() call.`

Here is my Flex component:

```javascript

import React from 'react';
import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
    row: (moreProps = {}) => ({
        display: 'flex',
        flexDirection: 'row',
        ...moreProps
    }),
    column: (moreProps = {}) => ({
        display: 'flex',
        flexDirection: 'column',
        ...moreProps
    })
});

const Flex = ({
    direction = 'row',
    justifyContent = 'flex-start',
    alignItems = 'stretch',
    children,
    style
}) => {

    return (
        <div {...stylex.props(styles[direction]({ justifyContent, alignItems }), style)}>
            {children}
        </div>
    );
};

export default Flex;

```

What could be wrong and what's a better to fixing this?

**Comment by nmn** [comment]
Only the *value* can be dynamic and not the keys.


This should work:

```ts
const styles = stylex.create({
    row: (moreProps = {}) => ({
        display: 'flex',
        flexDirection: 'row',
        ...moreProps
    }),
    column: (moreProps = {}) => ({
        display: 'flex',
        flexDirection: 'column',
        direction: moreProps.direction,
        alignItems: moreProps.alignItems,
        justifyContent: moreProps.justifyContent,
    })
});
```

This limitation cannot be removed since even in the case of dynamic styles, class names are generated and only variable values are set as inline styles.

**Comment by ebitogu** [comment]
@nmn  Thanks for your suggestions but the following piece of code in itself still doesn't work:


```javascript
const styles = stylex.create({
    row: {
        display: 'flex',
        flexDirection: 'row',
    },
    column: {
        display: 'flex',
        flexDirection: 'column',
    },
    place: (moreProps = {}) => ({  //This argument works if it's a simple primitive but Objects don't work
        alignItems: moreProps.alignItems,
        justifyContent: moreProps.justifyContent,
    })
});

```

It seems the arguments that are allowed as dynamic values are only primitives other than objects. 

It's weird, that the error below keeps coming up:
`
/app/common/components/ui/Flex/index.js: Only static values are allowed inside of a stylex.create() call.`

**Comment by nmn** [comment]
The pattern in your last example is designed to be supported. Looks like you've encountered a bug! I'll re-open this issue so we can fix this bug.

**Comment by ebitogu** [comment]
@nmn  Wow! You are right. The default value was the issue. It's working now after it was removed. Thank you

**Comment by nmn** [comment]
We will **not** be supporting default values within dynamic style functions. This issue is open as a reminder to improve compiler error messages when default values are encountered.
