### ISSUE TITLE
[NextJS]Applying stylex Styles to External Components

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#199]
Styling my own components using stylex is straightforward, but I'm facing a challenge when trying to apply styles to the Next.js Link component without resorting to inline CSS.
```javascript

import Link from "next/link";

const styles = stylex.create({
    title: {
        fontWeight: 600,
        fontSize: "22px",
        lineHeight: "26px",
        paddingBottom: "5px"
    },
    subHeadLine: {
        fontWeight: 500,
        fontSize: "13px",
        lineHeight: "16px",
        color: colors.secondaryText
    },
    cta: {
        color: colors.primaryColor,
        textDecoration: 'none',
        ':hover': {
            backgroundColor: colors.hoverColor
        }
    }
});

// ... other code ...

<Link href={'/signup'}>{cta}</Link></Text>
// ... other code ...

```

How can I apply the cta style defined using stylex to the Link component provided by Next.js in the code above?

**Comment by nmn** [comment]
I assume you solved your own problem. I just want to mention that you're using `:hover` wrong.


Use this instead. StyleX doesn't have the concept of "hover styles". StyleX has "conditions" within style values.

```ts
const styles = stylex.create({
    title: {
        fontWeight: 600,
        fontSize: "22px",
        lineHeight: "26px",
        paddingBottom: "5px"
    },
    subHeadLine: {
        fontWeight: 500,
        fontSize: "13px",
        lineHeight: "16px",
        color: colors.secondaryText
    },
    cta: {
        color: colors.primaryColor,
        textDecoration: 'none',
        backgroundColor: {
            default: null,
            ':hover': colors.hoverColor,
        }
    }
});
```

**Comment by thisizkp** [comment]
@nmn will it not be too ugly when trying to add multiple hover styles? We have to specify `:hover` within each style separately

**Comment by nmn** [comment]
@thisizkp Ugly? No. Verbose? Yes.

We prioritise consistency and composability over ability to write styles quickly. We made the decision to pseudo classes and media queries *within* CSS properties after a lot of thought and consideration.

The single biggest reason for this is composing styles. If you have a custom component that accepts arbitrary styles as a prop, and you pass in `margin: 0`. The margin should be `0`. Always. StyleX's model achieves this.

The traditional approach means you have to double check if a component has hover styles, and media queries and then manually override each of them separately, making style merging feel unreliable and finicky.

---

We have been working to reduce the boilerplate as much as possible. 
1. You can already use constants to avoid typing out long media queries repeatedly.
2. We are also implementing simple functions to help, so you may able to write something like this in the future:

```ts
const hover = (default, hover, active = null) => 
  ({ default, ':hover': hover, ':active': active });
const styles = stylex.create({
    title: {
        fontWeight: 600,
        fontSize: "22px",
        lineHeight: "26px",
        paddingBottom: "5px"
    },
    subHeadLine: {
        fontWeight: 500,
        fontSize: "13px",
        lineHeight: "16px",
        color: colors.secondaryText
    },
    cta: {
        color: pointerStyles(colors.secondary, colors.primary),
        textDecoration: 'none',
        backgroundColor: pointerStyles(null, colors.hoverColor),
    }
});
```

**Comment by thisizkp** [comment]
Sorry about that. Yeah, I meant verbose.
> Ugly? No. Verbose? Yes.

Excited for this 🎉 
> We are also implementing simple functions to help, so you may able to write something like this in the future

@nmn Thanks for the reply and for letting us know the thought process behind the API
