### ISSUE TITLE
stylex not working

### ISSUE THREAD

**Issue by lordeadroid** [facebook/stylex#201]
I have a project in React in typrscript. I tried to use stylex lib but got the error following error. I have followed all the instructions fropm the installation guide. I'm not sure if the error is due to typescript.
![Screenshot from 2023-12-17 15-43-43](https://github.com/facebook/stylex/assets/130520887/b815fa96-8d12-4e81-a179-80c7f1215ade)

**Comment by nmn** [comment]
Other than the fact that you tried to use `stylex.create` *within* a component, which is not allowed, I don't see anything wrong with your usage.

1. Please move the style declaration outside the function body.
2. Please tell me what kind of error this is. ESLint or Typescript.

**Comment by lordeadroid** [comment]
1. At first I used stylex.create outside the component and got the same error.
2. I think this is typescript error.

**Comment by nmn** [comment]
I'll need more context.

Here is an example app without typescript errors:
https://stackblitz.com/edit/stylex-next-untd91?file=app%2Flayout.tsx

- Perhaps you haven't installed `@stylexjs/stylex`?
- Have you added `import * as stylex from '@stylexjs/stylex';` at the top of the file?

**Comment by lordeadroid** [comment]
Sorry I didn't explain my problem clearly. Firstly I followed the instruction given in this https://stylexjs.com/docs/learn/installation/  After that didn't work as intended then I try to change code in hope of it will work (like declaring styles inside a React component). I have tried all the configs given in the docs like local development,  development and production config. If it is possible, you can look at the code https://github.com/lordeadroid/kart-cart in the stylex branch.
Thank You

**Comment by nmn** [comment]
I cannot see a `stylex` branch on the repo you shared. I'll wait till you can add it.

I also see that you are using a `create-react-app`, which would mean using the `@stylexjs/webpack-plugin`. We don't have an example of this yet, but there is an issue where there is discussion about the Webpack plugin that you might find helpful.

**Comment by lordeadroid** [comment]
I have removed stylex from main branch since I couldn't find a way to run it. I have added the stylex branch. And could you tell we which tool is working perfectly (like vite)

**Comment by nmn** [comment]
Rollup works best at the moment. I haven't tested the vite plugin myself, but `vite-plugin-stylex` is reportedly working well as well.

**Comment by nmn** [comment]
@iDenisM Using `const` in that location is a relatively new Typescript feature. You probably need to update Typescript for your project.

**Comment by sabirlkhaloufi** [comment]
![Screenshot from 2024-01-01 18-32-15](https://github.com/facebook/stylex/assets/83829858/d0a11a37-ef4e-49b1-afe9-dfcb81eb72fc)

i have this probleme in my project react + typescript + vite

**Comment by nmn** [comment]
@sabirlkhaloufi Have you set up a compiler? You should try `vite-plugin-stylex` or `vite-plugin-stylex-dev`.
