### ISSUE TITLE
Theme has insufficient type check

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#208]
**Is your feature request related to a problem? Please describe.**

Currently, `Theme` cannot check keys validity.

**Describe a solution you'd like**

I suggest to enforce keys typecheck in Theme by editing:

```ts
// @stylexjs/stylex/lib/StyleXTypes.d.ts

export type Theme<
  T extends VarGroup<unknown, symbol>,
  Tag extends symbol = symbol,
> = Tag &
  Readonly<{
    theme: StyleXClassNameFor<string, IDFromVarGroup<T>>; // string -> keyof T
  }>;
```

In the following example:

```ts
type IComponentVarKey =
  | 'hoverColor'
  | 'hoverOpacity';
export type IComponentVars = {
  [key in IComponentVarKey]?: string | StyleXVar<string>;
};
export type IComponentVarGroup = VarGroup<IComponentVars>;
export type IComponentTheme = Theme<IComponentVarGroup>;
```
`IComponentTheme` would become:

```ts
type IRippleTheme = symbol & Readonly<{
    theme: StyleXClassNameFor<"__tokens" | "__opaqueId" | typeof Symbol.toPrimitive | typeof Symbol.toStringTag | IRippleThemeVarKey | "toString" | "valueOf" | "description", symbol>;
}>
```

Instead of:

```ts
type IRippleTheme = symbol & Readonly<{
    theme: StyleXClassNameFor<string, symbol>;
}>
```

**Comment by nmn** [comment]
The `StyleXClassNameFor` is simply a string, so what you're proposing will not help. `StyleXClassNameFor` is represented as an object along with a `unique symbol` as a workaround (a lie) to make something that works like `opaque types` in Typescript.

This is useful to store type information even though the value itself is just a random string.

In the case of `theme` there are only two goals:
1. Be able to constrain themes for a particual Variable set (created using `defineVars`)
2. Conform to a type that is accepted by `stylex.props`

Both of these requirements are already satisfied and adding anymore specific types will be misleading and a worse experience.

**Comment by olivierpascal** [comment]
Well noted. So to be clear, today there is no way to enforce a theme to have specific vars, correct?

Usecase: a component accepts a theme from props. I want to enforce the theme to only contains vars 'hoverColor' and 'hoverOpacity'.

**Comment by olivierpascal** [comment]
> 1. Be able to constrain themes for a particular Variable set (created using `defineVars`)

I don't understand how Theme can do that, actually.

**Comment by olivierpascal** [comment]
Here is a full replicable example:

```tsx
import * as stylex from '@stylexjs/stylex';
import React from 'react';

export const varsA = stylex.defineVars({
  varA1: 'red',
});

export const themeA = stylex.createTheme(
  varsA,
  stylex.defineVars({
    varA1: 'green',
  }),
);

export const varsB = stylex.defineVars({
  varB1: 'red',
});

export const themeB = stylex.createTheme(
  varsB,
  stylex.defineVars({
    varB1: 'green',
  }),
);

export const MyComponent: React.FC<{ theme: typeof themeA }> = ({ theme }) => (
  <div {...stylex.props(theme)} />
);

export const Correct: React.FC = () => <MyComponent theme={themeA} />;

export const Incorrect: React.FC = () => <MyComponent theme={themeB} />; // should trigger a type error
```

Without modification, the last line does not trigger any type error.

With modification (`theme: StyleXClassNameFor<keyof T, IDFromVarGroup<T>>;`), the last line trigger an error, which is expected:

<img width="1087" alt="image" src="https://github.com/facebook/stylex/assets/2182039/94fb6b36-0c09-4529-85ee-c9339b3cd56c">

**Comment by olivierpascal** [comment]
@nmn is it something you would re-considerate, regarding this example?

**Comment by nmn** [comment]
Your usage is incorrect.

```ts
import * as stylex from '@stylexjs/stylex';
import React from 'react';

// Define a themeA

const varsA = stylex.defineVars({
  varA1: 'red',
});

const themeA = stylex.createTheme(
  varsA,
  {
    varA1: 'green',
  },
);

// Define a themeB

const varsB = stylex.defineVars({
  varB1: 'red',
});

const themeB = stylex.createTheme(
  varsB,
  {
    varB1: 'green',
  },
);
```

Try this and let me know what's not idea about the types.

**Comment by nmn** [comment]
There is indeed a type error that is not occurring. I'll re-open the issue.

**Comment by nmn** [comment]
@olivierpascal In the meantime, this is a way to get the type-safety you want:

```ts
declare const VarsA: unique symbol;
const varsA = stylex.defineVars<{varA1: string}, typeof VarsA>({
  varA1: 'red',
});


const themeA = stylex.createTheme(varsA, {
  varA1: 'green',
});

// Define a themeB

declare const VarsB: unique symbol;
const varsB = stylex.defineVars<{varB1: string}, typeof VarsB>({
  varB1: 'red',
});

const themeB = stylex.createTheme(varsB, {
  varB1: 'green',
});

// Create a themeable component, allowing only themeA type

const MyComponent: React.FC<{ theme: Theme<typeof varsA> }> = ({ theme }) => (
  <div {...stylex.props(theme)} />
);

// Error
const x: Theme<typeof varsA> = themeB;

const Correct: React.FC = () => <MyComponent theme={themeA} />;

const Incorrect: React.FC = () => <MyComponent theme={themeB} />; // Errors
```

**Comment by olivierpascal** [comment]
And what do you think about the mentioned patch? (`theme: StyleXClassNameFor<keyof T, IDFromVarGroup<T>>;)`)

**Comment by nmn** [comment]
@olivierpascal It's not quite good enough. It will break some of the upcoming features for theming.
