### ISSUE TITLE
stylex.keyframes() does not accept vars

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#214]
**Is your feature request related to a problem? Please describe.**

```ts
const grow = stylex.keyframes({
  '0%': { borderWidth: '0' },
  '100%': { borderWidth: vars.activeWidth },
});
```

Always leads to `Only static values are allowed inside of a stylex.create() call.`.

I don't know if this is expected, but this limitation is not mentioned in https://stylexjs.com/docs/api/javascript/keyframes/.

**Describe a solution you'd like**

stylex.keyframe() to accept vars.

**Comment by nmn** [comment]
Thanks for finding this bug.
