### ISSUE TITLE
Coherency between border and outline

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#215]
**The problem**

In one hand, you are discouraging some shorthand properties (ie. border). In another hand, some shorthand properties are encouraged (ie. outline).

**How to reproduce**

```ts
const styles = stylex.create({
  container: {
    outlineWidth: '1px',
    outlineStyle: 'solid',
  }
});
```

`'outlineWidth' is not supported yet. Please use 'outline' instead`

`'outlineStyle' is not supported yet. Please use 'outline' instead`

Any reason?

**Comment by nmn** [comment]
The reasons are historical and not important at this point. We already have a task to allow all of these properties.
