### ISSUE TITLE
Implementation of Intellisense for CSS Properties in Stylex

### ISSUE THREAD

**Issue by LeoVitale** [facebook/stylex#216]
**Is your feature request related to a problem? Please describe.**

I'm currently experiencing a lack of a significant feature in Stylex within VS Code, which is available in tools like Vanilla Extract. Specifically, it's the ability of Intellisense to display CSS properties while I am styling. This absence hinders efficiency and accuracy in writing CSS code.

**Describe the solution you'd like**

I would like Stylex to be enhanced to integrate Intellisense within VS Code, enabling developers to view available CSS properties while coding. This functionality would significantly boost productivity and help avoid common mistakes, making the CSS writing process more intuitive and efficient.

**Describe alternatives you've considered**

An alternative would be to continue using tools like Vanilla Extract or other plugins that offer this feature. However, this does not solve the issue for those who prefer or need to use Stylex for its unique features and integration with other systems.

**Additional context**

This enhancement would not only benefit my workflow but also be valuable for many other developers using Stylex in VS Code. The addition of this feature would put Stylex on par with other market tools, increasing its attractiveness and usability.

![image](https://github.com/facebook/stylex/assets/997045/d4f9ff42-4d79-4d15-867c-0c191433b6fe)

**Comment by LeoVitale** [comment]
Obs: The only way that I found to do what I wanted was importing this `CSSPropertiesWithExtras` type

![image](https://github.com/facebook/stylex/assets/997045/c4589498-acf1-428b-b888-2230cc5672e9)

**Comment by nmn** [comment]
This issue has already been fixed and will be in the next release.
