### ISSUE TITLE
how to use creatTheme to change website theme dark or light mode ,the  createTheme api document is too simple，please give some example 。thx

### ISSUE THREAD

**Issue by susakin** [facebook/stylex#218]
**The problem**

**How to reproduce**

Steps to reproduce:
1.
2.
3.

**Expected behavior**

**Environment (include versions). Did this work in previous versions?**

**Comment by nedjulius** [comment]
hey @susakin , I suggest you take a look at this issue https://github.com/facebook/stylex/issues/122

**Comment by susakin** [comment]
thx
