### ISSUE TITLE
Docs examples contains unrelated styles

### ISSUE THREAD

**Issue by steida** [facebook/stylex#231]
https://stylexjs.com/docs/learn/theming/defining-variables/
https://stylexjs.com/docs/learn/theming/using-variables/
https://stylexjs.com/docs/learn/theming/creating-themes/

```ts
export const colors = stylex.defineVars({
  primaryText: {default: 'black', [DARK]: 'white'},
  secondaryText: {default: '#333', [DARK]: '#ccc'},
  accent: {default: 'blue', [DARK]: 'lightblue'},
  background: {default: 'white', [DARK]: 'black'},
  lineColor: {default: 'gray', [DARK]: 'lightgray'},
  borderRadius: '4px',
  fontFamily: 'system-ui, sans-serif',
  fontSize: '16px',
});
```

borderRadius. fontFamily, fontSize are not colors.

**Comment by tushar-nath** [comment]
@nmn - Can you please provide some pointers on this? I would love to contribute to this.

**Comment by tushar-nath** [comment]
@nmn - I have raised a PR for this, would appreciate your review on it.
