### ISSUE TITLE
CSS output inconsistency between builds

### ISSUE THREAD

**Issue by mrmntte** [facebook/stylex#232]
**The problem**
`npm run build` doesn't include all/some classes in the final css file.
Usually only the first build (without .next/ cache) is generated correctly, but it's inconsistent.
I'm not sure if this also makes it happen randomly with `npm run dev` when navigating between routes.

all classes are missing:
![image](https://github.com/facebook/stylex/assets/49642108/b44b34c1-b5f8-438b-bebc-00850412597a)

some:
![image](https://github.com/facebook/stylex/assets/49642108/c843329b-d2ca-4b49-9090-7589c16098df)

**How to reproduce**
run multiple times `npm run build && npm run start`
https://stackblitz.com/edit/github-kh7iw4?file=app%2Flayout.tsx

**Expected behavior**
![image](https://github.com/facebook/stylex/assets/49642108/f3ff6354-cfb2-4c58-aea0-4d86da830ab4)

**Comment by steida** [comment]
I also have to occasionally remove .next dir to refresh styles.

**Comment by nmn** [comment]
This is a known issue which is why the NextJS example in the repo does this:

```json
"clean": "rimraf .next",
"predev": "npm run clean",
"prebuild": "npm run clean",
```

I've already reached out to the NextJS team for help. In the meantime, I'll fix the Stackblitz example.
