### ISSUE TITLE
Is it possible to pass an array of elements corresponding to screen widths?

### ISSUE THREAD

**Issue by VeskoPL** [facebook/stylex#239]
Trying to create Grid component.

```
const styles = stylex.create({
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, 1fr)'
  },
})

function Grid({ columns = [1, 2, 4, 8], children, ...props }) {

  const responsiveGridTemplateColumns = {
    default: `repeat(${columns[0]}, 1fr)`,
    [`@media (min-width: 600px)`]: `repeat(${columns[1]}, 1fr)`,
    [`@media (min-width: 1200px)`]: `repeat(${columns[2]}, 1fr)`,
    [`@media (min-width: 1800px)`]: `repeat(${columns[3]}, 1fr)`,
  };

  return (
    <div {...props} {...stylex.props({ ...styles.grid, { gridTemplateColumns: responsiveGridTemplateColumns } })}>
      {children}
    </div>
  );
}
```

**Comment by necolas** [comment]
All stylex code must be authored outside of component bodies. Please see the stylex docs for the correct syntax for media queries and other property value qualifiers: https://stylexjs.com/docs/learn/styling-ui/defining-styles/#creating-styles

**Comment by nmn** [comment]
@VeskoPL This is the closest to what you want.

```tsx
const styles = stylex.create({
  grid: (columns) => ({
    display: 'grid',
    gridTemplateColumns: {
      default: `repeat(${columns[0]}, 1fr)`,
      '@media (min-width: 600px)': `repeat(${columns[1]}, 1fr)`,
      '@media (min-width: 1200px)': `repeat(${columns[2]}, 1fr)`,
      '@media (min-width: 1800px)': `repeat(${columns[3]}, 1fr)`,
    },
  }),
});

function Grid({ columns = [1, 2, 4, 8], children, ...props }) {
  return (
    <div {...props} {...stylex.props({ ...styles.grid(columns) })}>
      {children}
    </div>
  );
}
```

**Comment by VeskoPL** [comment]
@nmn Since we are not allowed to use conditions inside the stylex.create function, the only way to define a single prop is by creating an additional object, is that correct?

P.S. We don't always want to pass four values for four corresponding screen widths (styles.grid), so it can be overwhelming to define a new object for other cases, tbh.

```
const styles = stylex.create({
  grid: (columns) => ({
    display: 'grid',
    gridTemplateColumns: {
      default: `repeat(${columns[0]}, 1fr)`,
      '@media (min-width: 600px)': `repeat(${columns[1]}, 1fr)`,
      '@media (min-width: 1200px)': `repeat(${columns[2]}, 1fr)`,
      '@media (min-width: 1800px)': `repeat(${columns[3]}, 1fr)`,
    },
  }),
  grid1: (columns) => ({
    display: 'grid',
    gridTemplateColumns: `repeat(${columns}, 1fr)`,
  }),
});

function Grid({ columns = [1, 2, 4, 8], children, ...props }) {
  return (
    <div {...props} {...stylex.props(type of columns === "string" ? styles.grid1(columns) : styles.grid(columns))}>
      {children}
    </div>
  );
}
```

**Comment by nmn** [comment]
> P.S. We don't always want to pass four values for four corresponding screen widths (styles.grid)

This is why the API is designed the way it is. If you override the given styles with a different value for `gridTemplateColumns` all the media queries will be removed as well. You don't have to re-use the same 4 media queries every time.

----

If I misunderstood and you're talking about the amount of typing needed to repeat the media queries over and over again, there is an RFC for sharing media query constants across an entire project. You can use `const` to define them locally.

----

Finally, when you find yourself using so many media queries, it is a good idea to look into alternatives that don't need them at all. E.g. in your example, `auto-fit` or `auto-fill` migh be a better solution to define adaptive grid columns without resorting to media queries.
