### ISSUE TITLE
Theme should be able to selectively overwrite vars based on which is defined or not

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#242]
**Is your feature request related to a problem? Please describe.**

I would like to have an option to make `stylex.createTheme()` to selectively overwrite vars, instead of overwriting all vars from the base var group.

Here is my usecase:

A themeable Button, themed by a global theme, which could be selectively overridden by a variant theme (ie. Rounded Button, Filled Button, Outlined Button, Elevated Button, ...), which could be selectively overridden by a theme provided in props (ie. Blue Rounded Button).

Today it is not possible to do so, because each theme embed all base vars, so I cannot just create a variant with a different text color.

Also, it is not possible to just copy all the base var group because it depends of the global/variant theme used.

```ts
// tokens.stylex.ts
import * as stylex from '@stylexjs/stylex';

const vars = {
  background: 'transparent',
  size: '40px',
  borderRadius: 'none',
  // ...a lot of other properties
};

export const styleXVars = stylex.defineVars(vars);
export const globalTheme = stylex.createTheme(styleXVars, vars);
```

```tsx
import React from 'react';
import * as stylex from '@stylexjs/stylex';

import { styleXVars, globalTheme } from './tokens.stylex';

// Variant: make a Rounded Button
const roundedTheme = stylex.createTheme(styleXVars, {
  borderRadius: '10px',
});

const styles = stylex.styles({
  container: {
    backgroundColor: styleXVars.background,
    // ...
  },
});

export const RoundedButton = ({ overridenTheme = undefined }) => {
  const globalTheme = useComponentTheme('Button'); // returns globalTheme
  const variantTheme = useComponentTheme('RoundedButton'); // returns roundedTheme

  return <div {...stylex.props({ globalTheme, variantTheme, userTheme, styles.container })}>...</div>
};

// Possible usage: make a blue rounded button
// const blueRoundedTheme = stylex.createTheme(styleXVars, { background: 'blue' });
// <RoundedButton overridenTheme={blueRoundedTheme} />
```

You may say that it does not comply with the stylex philosophy or, or that my usage is incorrect, but i would love to hear from you about this usecase. Thanks.

**Comment by nmn** [comment]
This is already fixed on `main` and will be in the next release.

**Comment by olivierpascal** [comment]
Just to be sure that we are on the same page @nmn, I am not talking about the typing limitation that requires all group var to be overwritten in a theme (https://github.com/facebook/stylex/issues/188), but rather the way that the vars are overwritten (the entire var group is always overwritten even if only one var is set in theme).
