### ISSUE TITLE
Difficulty Applying stylex Hover Effect to Ant Design Button in Version 5

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#243]
I'm currently facing challenges while attempting to use stylex to apply a hover effect to an Ant Design Button in version 5. Specifically, I'm trying to implement the hover effect from the "cta" style, but it doesn't seem to be working as expected.

```javascript
import { Typography, Flex, Button } from "antd";

const styles = stylex.create({
    cta: {
        ":hover": {
            backgroundColor: "#316FF6"
        }
    }
});

<Button type={"link"} href={ctaLink}  {...stylex.props(styles.cta)}>{cta}</Button>

```

I'm using Ant Design version 5 in my project.

Despite applying the stylex hover effect as described in the "cta" style, the desired change in background color (#316FF6) upon hover is not taking place.

Any ideas on how to go about this will be greatly appreciated. Thank you

**Comment by nmn** [comment]
1. Start by using the correct way to use hover styles:

```ts
const styles = stylex.create({
    cta: {
        backgroundColor:  {
            default: "<base color here>",
            ":hover": "#316FF6"
        }
    }
});
```

2. Try rendering a plain div to verify that StyleX is set up correctly in your project
3. Check if the `Button` component accepts the `className` and `style` props.

**Comment by ebitogu** [comment]
Oh, my bad. That's true, it worked. Thanks for the correction.
