### ISSUE TITLE
Question regarding pseudoclass challenges

### ISSUE THREAD

**Issue by Chris-Mits** [facebook/stylex#250]
Hello there, hope you are doing well.

We are actively considering the integration of StyleX into our component library (currently written in native CSS w/ postCSS for certain needed features). While experimenting with StyleX, we encountered a few instances in our stylesheets where a style is being applied to a specific child element when a parent element receives a certain pseudoclass (e.g., `:hover` or `:focus-within`).

We understand that this functionality is currently not supported within StyleX, and the only way to achieve "_styles at a distance_" is through inheritable CSS properties like `color` and `font`, among others.

I was wondering if there is any kind of workaround to achieve something similar to the following:

```
// Simple example:

.parent:hover .child {
  background-color: magenta;
}
```
```
// Another common example in our codebase using CSS nesting syntax:

.wrapper:focus-within {
    box-shadow: var(--input-border-shadow);

    .child {
      border-color: var(--input-border-color-focused);
    }
}
```

Thank you for your time

**Comment by nmn** [comment]
As you understand, currently the only way to achieve this is by using inheritable CSS properties. However, this includes CSS variables.

```tsx
// component.stylex.ts
export const vars = stylex.defineVars({
  bgColor: 'transparent',
  borderColor: 'transaprent',
});
```

```tsx
// MyComponent.ts
import {vars} from './component.stylex';

const styles = stylex.create({
  parent: {
    [vars.bgColor]: {
      default: null, // or value when not hovering
      ':hover': 'magenta',
    },
  },
  child: {
    backgroundColor: vars.bgColor,
  },
})
```

You can do this same for `:focus-within` as well.

------

We will be adding first-class support early next year in a way that doesn't cause "styling at a distance".

**Comment by Chris-Mits** [comment]
Thank you!
