### ISSUE TITLE
[plugin:vite-plugin-stylex] C:\Users\Arun\Documents\GitHub\black\packages\frontend\src\components\buttons\Button.tsx: Only static values are allowed inside of a stylex.create() call.

### ISSUE THREAD

**Issue by arunnan** [facebook/stylex#259]
Created tokens.stylex.ts as below.

```tsx
import * as stylex from '@stylexjs/stylex';

const DARK = "@media (prefers-color-scheme: dark)";

export const colors = stylex.defineVars({ 
    primary: {default: '#fff', [DARK]: '#000'},
    primaryDark: {default: '#ccc', [DARK]: '#333'},
    bg: {default: '#fff', [DARK]: '#000'},
    white: {default: '#fff', [DARK]: '#000'},
    black: {default: '#000', [DARK]: '#fff'}
})
```

and Buttons.tsx as below

```tsx
import * as stylex from '@stylexjs/stylex';
import { ComponentProps } from "react";
import { colors } from 'src/components/tokens.stylex';

type ButtonProps = {
    variant?: "primary",
    children?: React.ReactNode,
    styles?: stylex.StyleXStyles,
} & ComponentProps<"button">

const baseStyle = {
    borderWidth: '1px',
    borderStyle: 'solid',
    color: colors.white,
    borderRadius: '5px',
    cursor: 'pointer',
    padding: '10px 15px'
};

const s = stylex.create({
    base: baseStyle,
    primary: {
        borderColor: {
            default: colors.primary
        },
        color: {
            default: colors.black
        },
        backgroundColor: {
            default: colors.primary,
            ':hover': colors.primaryDark,
            ':focus': colors.primaryDark,
            ':active': colors.primaryDark,
        },
    }
});

const Button = ({ variant = "primary", styles, ...props }: ButtonProps) => (
    <button {...stylex.props(s.base, s[variant], styles)} {...props} />
);

export default Button;
```

I am getting the below error

`[plugin:vite-plugin-stylex] C:\Users\Arun\Documents\GitHub\black\packages\frontend\src\components\buttons\Button.tsx: Only static values are allowed inside of a stylex.create() call.`

Kindly suggest a fix.

**Comment by nmn** [comment]
The problem is with the import:

```js
import { colors } from 'src/components/tokens.stylex';
```

You need to use relative paths to actual file. StyleX doesn't know about aliases set up in the `tsconfig`. 


```js
import { colors } from '../tokens.stylex';
```


----

Why is `baseStyles` defined as a separate constant object?

**Comment by arunnan** [comment]
I have used the relative path, still it is not working.

**Comment by nmn** [comment]
@arunnan I'm not sure if `vite-plugin-stylex` is passing the correct configuration to the Babel plugin. Try passing the `unstable_moduleResolution` option to it manually.

**Comment by arunnan** [comment]
@nmn I've updated all my dependencies and moved stylex() before all the plugins, but I'm still facing the issue.

**Comment by nmn** [comment]
@arunnan It might also be useful to:

1. Try the other Vite plugin for StyleX (see: https://stylexjs.com/docs/learn/ecosystem/#vite)
2. Create an issue for `vite-plugin-stylex`

Other than that, share more details about your build setup if you want more help. 
I don't have enough context about your project to help any further.
