### ISSUE TITLE
SVG properties support for eslint-plugin

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#266]
**Is your feature request related to a problem? Please describe.**

eslint-plugin should supports svg properties.

**Describe a solution you'd like**

```ts
const styles = stylex.create({
  circle: {
    cx: '50%',
    cy: '50%',
    strokeDasharray: '100',
    fill: 'transparent',
  },
  // ...
}
```

**Describe alternatives you've considered**

`// eslint-disable`

**Comment by nmn** [comment]
I'll add it to the list of missing properties in the ESLint plugin. Thanks.

**Comment by nmn** [comment]
@olivierpascal Not every SVG attribute can be applied using CSS. In your example, `strokeDasharray` and `fill` should work already, but `cx` and `cy` are intentionally not supported.

`cx` and `cy` attributes can be applied with CSS in the SVG 2.0 spec. However, this spec isn't consistently applied across browsers and supporting it officially would be harmful.

Outside of this, I'm adding any missing SVG property to the ESlint rule.
