### ISSUE TITLE
[NextJS] Usage with Pages Router

### ISSUE THREAD

**Issue by aspectiscool** [facebook/stylex#269]
Are there any examples on how to use StyleX with the NextJS Pages Router? My team and I have been against migration to the new app router and it seems like StyleX only has app router examples available.

Has anyone else tried (and successfully) used it w/ pages?

Thanks again!

**Comment by nmn** [comment]
I'm currently blocked on making Pages router work. I'll leave this issue open for when I get it working.

That said, using the `app` router for just a layout seems to work even if the rest of your app is using `pages`.

**Comment by nmn** [comment]
Quick update, I found a bug in the dev-mode runtime style injection and once I fix that things work with the pages router with Next 14. I'll add an example to the repo before I release the next version of StyleX with the fixes.

**Comment by nmn** [comment]
After the latest StyleX release 0.4.1, pages router works without any big changes to the example set up.

Here's a link to my demo project. I have added a `pages` branch.

https://github.com/nmn/nextjs-app-dir-stylex/tree/pages

**Comment by arthurur** [comment]
@nmn my project is in a migration state from using the `pages` router to the `app`, so I currently have both folders being used. 

I've been getting server/client mismatch errors and styles are not being applied to my `page` files in the `app` folder, though I noticed I does work if I add the `"use client"` directive.

Am I missing a config, or using both folders with mixed client and server components are not supported yet?

**Comment by nmn** [comment]
@arthurur While we're working on bigger improvements, when I tried some basic splitting for `app` and `pages` dirs, things seemed to work in the project I shared above.

What version of next are you on? (We've seen issues with v14.0.4)

Can you provide a minimal reproduction? Perhaps by forking the example I shared above?

**Comment by arthurur** [comment]
@nmn Sorry for the delay, it took me a bit to figure it out. The issue was not quite what I thought. It was because I didn't have a `globals.css` or any `.css` import on my root `layout.tsx`. Having that fixed it.
