### ISSUE TITLE
Create with Props

### ISSUE THREAD

**Issue by ivoilic** [facebook/stylex#284]
**Is your feature request related to a problem? Please describe.**
The current syntax for applying stylex props in React is overly verbose for simple use cases:
```jsx
const styles = stylex.create({
  container: {
    color: 'red'
  },
});

<div {...stylex.props(styles.container)} />
```

**Describe a solution you'd like**
While having `stylex.prop` seperate from `stylex.create` makes sense for cases with multiple and/or dynamic classes, in a lot of instances it's vestigial code. I'd love a utility to generate props for all the styles and add them to the object. Something like this:

```jsx
const styles = stylex.createWithProps({
  container: {
    color: 'red'
  },
});

<div {...styles.container.props} />
```

This could also exist as a wrapper function. Any of these would be an improvement:

```jsx
const styles = stylex.create({
  container: {
    color: 'red'
  },
});

const props = stylex.withProps(styles);

<div {...props.container} />
```

**Describe alternatives you've considered**
Of course this is not a super complex utility for developers to write themselves or it could exist as a simple utility package. However, I think there is a lot of DX value to be gained by including it in the main package. This functionality could also just be added to `stylex.create` but I assume there would be performance downsides at scale?

**Comment by nmn** [comment]
You can use named imports and short names:

```tsx
import {create as c, props as p} from '@stylexjs/stylex';

const s = c({
  container: {
    color: 'red'
  },
});

<div {...p(s.container)} />
```

Does this solve your problem?

**Comment by ivoilic** [comment]
@nmn Thank you for responding. Aliasing doesn't really help, it shaves off some characters for sure, but it makes the code less legible. My solution removes the need to wrap ever single style in a function while still giving someone reading the line context as to what the object being spread is. This is not a question but more of a suggestion/RFC.

**Comment by necolas** [comment]
We explain in the docs why we don't value terse code for simple use cases, especially when it comes at the expense of over-complicating the API and not being practical for other use cases. This philosophy is similar to the one React follows, where the preference is to have one way to do things that works in all cases.

Ergonomic alternatives don't need to be built into StyleX itself. For example, in another library we'll be open sourcing you're able to pass the result of `create` calls directly to elements (i.e., `<html.div style={styles.container" />`), with either a runtime wrapper to close over `stylex.props` calls or a build-time transform to convert it to the more verbose form. This is even cleaner than what you're proposing, and it covers all the other uses cases not just simple ones.

Internally at Meta we use React to create components, so the majority of developers that are working with React and StyleX are already passing styles directly to a composite component via a prop (e.g., `style` or `xstyle` or whatever you want to call it) and only a minority of cases involves styling HTML elements directly. Typically the people spending the most time styling the raw HTML elements are the engineers working on design system components that everyone else then uses.

**Comment by ivoilic** [comment]
@necolas thanks for the in-depth explanation! The other library not being open yet explains a lot. Really appreciate you taking the time.
