### ISSUE TITLE
Intermittent Stylex Styles Issue in Next.js Application, Especially with Cache in Production Environment

### ISSUE THREAD

**Issue by yonatan2703** [facebook/stylex#286]
**The problem**

In my Next.js application, I am encountering an issue with the Stylex library. At times, when running the application, Stylex styles fail to appear. A temporary fix is to remove the `.next` folder and rerun the application. However, a more significant issue arises in production: when deploying the application using Next.js cache, the styles do not work in the browser, although the classes are present. This problem is concerning because I wish to use the cache feature to speed up application build times (Deploying the application with SST).

**How to reproduce**

Steps to reproduce:
1. Run the Next.js application with Stylex styles.
2. Observe that sometimes the styles do not appear.
3. Remove the `.next` folder and rerun the application, noting that the styles now appear.
4. In a production environment, deploy the application using Next.js cache.
5. Notice that the styles are not working in the browser, even though the classes are visible.

**Expected behavior**

I expect the Stylex styles to consistently appear when running the application, both in the development and production environments. Additionally, I expect the styles to function correctly in the browser when deploying the application with Next.js cache, as this is crucial for optimizing build times.

**Environment (include versions). Did this work in previous versions?**

- Next.js version: 14.0.4
- Stylex version: 0.4.1
- SST: 2.38.7
- Operating System: ubuntu 22.04 (WSL)

This issue was not observed in previous versions of Next.js or Stylex (if applicable, specify the last working version).

**Comment by besSejrani** [comment]
I have the same issue since v0.4.1 for my UI component library. Some of the styles doesn't appear.

**Comment by steida** [comment]
I had to disable the Vercel cache because of Nextra. https://github.com/shuding/nextra/issues/2526#issuecomment-1837180395

> There are only two hard things in Computer Science: cache invalidation and naming things.

**Comment by nmn** [comment]
This is a known issue in the Next plugin. If you see our example Next app, we delete the `.next` folder as `prebuild` script.

I've reached out to folks at Vercel and hopefully we can fix the issues early next year.

NOTE: StyleX's Babel plugin is *very* caching friendly.

**Comment by steida** [comment]
Note for PNPM users: pre* scripts must be explicitly enabled in the PNPM config via some cli command.

**Comment by nmn** [comment]
I have created a new Issue #297 that describes the issue with Webpack and NextJS. I got this information directly from Tobias Koppers. Please follow that issue as we attempt the various approaches to fix this problem.

As such I'm closing this issue. Please mention anything of value on that issue.

**Comment by steida** [comment]
`pnpm config set enable-pre-post-scripts true`

**Comment by derekjwilliams** [comment]
> This is a known issue in the Next plugin. If you see our example Next app, we delete the `.next` folder as `prebuild` script.
> 
> I've reached out to folks at Vercel and hopefully we can fix the issues early next year.
> 
> NOTE: StyleX's Babel plugin is _very_ caching friendly.

I may have tracked down the issue, at least in my case.  Comparing "non-working" .next folder contents to "working" I found a difference that seems to cause the issue. The css file of the "working" version, located in .next/static/a2a455ca88da9b14.css was different than the "non-working" version (that also had a different auto generated name, f23adbf2efd594d1.css). The "non-working" version is significantly shorter.

My .babel-rc

```module.exports = {
  presets: ['next/babel'],
  plugins: [
    ['@babel/plugin-transform-private-methods'],
    [
      '@stylexjs/babel-plugin',
      {
        dev: process.env.NODE_ENV === 'development',
        runtimeInjection: false,
        genConditionalClasses: true,
        treeshakeCompensation: true,
        unstable_moduleResolution: {
          type: 'commonJS',
          rootDir: __dirname,
        },
      },
    ],
  ],
  env: {
    development: {
      compact: false,
    },
  },
}
```

My package.json

```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@babel/runtime": "^7.24.0",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@stylexjs/babel-plugin": "^0.5.1",
    "@stylexjs/open-props": "^0.5.1",
    "@stylexjs/stylex": "^0.5.1",
    "@supabase/ssr": "latest",
    "@supabase/supabase-js": "latest",
    "@tanstack/react-query": "^5.28.6",
    "@tanstack/react-query-devtools": "^5.28.4",
    "axios": "^1.6.8",
    "next": "latest",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hot-toast": "^2.4.1",
    "sharp": "^0.33.2",
    "typescript": "5.3.3"
  },
  "devDependencies": {
    "@babel/plugin-transform-private-methods": "^7.24.1",
    "@stylexjs/eslint-plugin": "^0.5.1",
    "@stylexjs/nextjs-plugin": "^0.5.1",
    "@types/node": "20.11.5",
    "@types/react": "18.2.48",
    "@types/react-dom": "18.2.18",
    "encoding": "^0.1.13",
    "eslint-config-next": "14.1.3",
    "prettier-plugin-stylex-key-sort": "^1.0.1"
  }
}
```

**Comment by nmn** [comment]
@derekjwilliams Are you deleting your `.next` folder between builds? That might be the issue at hand since we know that caching is broken with the Next plugin today.

**Comment by derekjwilliams** [comment]
> #297

Thanks nmn, that was indeed the case. Fixed a while ago, sorry for not responding sooner

**Comment by yonatan2703** [comment]
If someone ever gets to this thread, this library solved all of my issues with using stylex + nextjs
Now I don't need to delete the `.next` directory with a `predev` script and I can use caching in my github actions
Works with styles version 0.7.5

https://github.com/SukkaW/stylex-webpack

**Comment by nmn** [comment]
There is also a community-made SWC plugin. 

https://github.com/Dwlad90/stylex-swc-plugin

We hope to support the development of this directly going forward.
