### ISSUE TITLE
Plugin for sorting style keys

### ISSUE THREAD

**Issue by steida** [facebook/stylex#287]
Tailwind has such a plugin: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier.

Is it a good idea to have something similar for StyleX? 🤔

**Comment by nmn** [comment]
This *is* a good idea and something that is planned but we can't prioritise. Thanks for creating the issue and hopefully someone can take this on.

The easiest solution is a fork of the `sort-keys` ESLint plugin that put the `@` and `:` at the end of the list. The actual specificity of at-rules and pseudo-classes can be used to sort in the actual order within a property too.

Hopefully a contributor can do this work?

**Comment by nedjulius** [comment]
hey, I will take a stab at this. seems interesting

**Comment by nedjulius** [comment]
hey, just wanted to inform interested parties that I am still looking into this issue. just didn't have much time to invest lately.

**Comment by nmn** [comment]
@nedjulius If someone starts working on this, we'll comment here to let you know!

**Comment by necolas** [comment]
Is this about sorting the namespace keys, or the property keys? Is it safe to reorder property keys for every resolution option available in the compiler?

**Comment by nmn** [comment]
@necolas This is about property keys. And from what I've seen it's always safe to sort property keys as long as standard CSS properties are used. And the main driver for the idea is to ensure properties are ordered by shorthand first, then long hand, then pseudo elements and not alphabetical.

**Comment by nedjulius** [comment]
alright, I started working on this issue. before I make any further strides, I would like you to evaluate some of the assumptions that I am currently making:
- we are only concerned about sorting the style property keys and pseudo-classes (`:hover`, `@media` etc.)
- because of the assumption above, we only care about evaluating the sorting within class names inside `stylex.create`, `stylex.keyframes`, `create` and `keyframes`; we do not care about sorting the class names
- we allow ascending and descending order, with the former being alphabetic, then `:..` pseudo classes, then `@...` pseudo classes and the latter reverse

**Comment by nmn** [comment]
> we allow ascending and descending order

We will only allow ascending order. Essentially all style keys will be sorted alphabetically, then `@` at-rules then `:` pseudo classes and `::` pseudo elements will be the very last. The same rules will apply to nested objects.

For the order within at-rules, pseudo classes and pseudo-elements, look at this file:

https://github.com/facebook/stylex/blob/main/packages/shared/src/utils/property-priorities.js#L0-L1

**Comment by nedjulius** [comment]
what would be the sorting for spread styles? say we have something like this:
```
const reusableStyles = { display: 'flex' }
const styles = stylex.create({
  foo: {
    position: 'relative',
    ..reusableStyles,
  }
});
```
is this even allowed? I tried compiling such example and it worked.

**Comment by nmn** [comment]
@nedjulius When the object is defined locally in the same file, that is allowed. You can also use `stylex.include` to spread styles from another file that have already been compiled using `stylex.create`.


The ESLint plugin should leave the spread in place and sort the keys and before and after as separate groups.

**Comment by zaydek** [comment]
> hey, just wanted to inform interested parties that I am still looking into this issue. just didn't have much time to invest lately.

Just to confirm -- `stylex.include` is supported just not documented, right?

Also if it helps @nedjulius with prior art, I created and closed this issue in favor of this one. Will past the relevant text here:

> One the killer user cases of traditional CSS is that you could use Stylelint and write a configuration file that describes the idealized order of properties. This is then enforced via VS Code plugin that draws underline squigglies when any of the properties are out of the idealized order, with the optionality to suppress ordering complaints if there's a good reason, e.g. // stylelint-disable or something like that. Unfortunately Stylelint didn't work quite well for SASS but I was able to run Stylelint on the .css output to the same effect.
>
> This was a massive time saver because it meant there was no ambiguity about what ordering should look like, users can define their own idealized arrays in a configuration file, and VS Code was able pick up all of this. Sort of like Prettier for CSS property order.
