### ISSUE TITLE
Only static values are allowed inside of a stylex.create() call

### ISSUE THREAD

**Issue by k14lb3** [facebook/stylex#295]
**The problem**

Creating a barrel file for `stylex` vars then importing the vars using the barrel causes an `Only static values are allowed inside of a stylex.create() call` error. 

```
// ./styles/vars.stylex.ts

export const color = stylex.defineVars({
  black: '#000000',
});
```

```
// ./styles/index.ts

export * from './vars.stylex';
```

**Environment (include versions). Did this work in previous versions?**

```
@stylexjs/stylex@0.4.1
```

**Comment by nmn** [comment]
Creating a `barrel file for stylex vars` is not allowed. This part of the core design of stylex. The file where the variable is being imported needs to statically know the file path where the variables were defined.
