### ISSUE TITLE
all is not supported

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#312]
**The problem**

```
Module build failed:
Error: styles.ts: all is not supported
```

**How to reproduce**

```ts
// styles.ts
const styles = stylex.create({
  container: {
    // https://developer.mozilla.org/en-US/docs/Web/CSS/all
    all: 'unset',
  },
});
```

**Expected behavior**

`all` css property support

**Comment by nmn** [comment]
This is intentional. `all` by definition unsets too many styles and breaks encapsulation. If you need to use it for a CSS reset, put it in a CSS file.
