### ISSUE TITLE
stylex.create({}) show error `TS2554: Expected  0  arguments, but got  1`

### ISSUE THREAD

**Issue by romanchekashov** [facebook/stylex#313]
Please remove `const` from:
```
export type Stylex$Create = <
  const S extends {
    [key: string]: UserAuthoredStyles | ((...args: any) => UserAuthoredStyles);
  },
>(
  styles: S,
) => MapNamespaces<S>;
```
https://github.com/facebook/stylex/blob/a3528b69d567bcf5c61c6e92e86312bcac8e6122/packages/stylex/src/StyleXTypes.d.ts#L108

**Comment by romanchekashov** [comment]
I've created a pull request with fix: https://github.com/facebook/stylex/pull/314

**Comment by nmn** [comment]
The `const` is needed. Without it, the types aren't specific enough.

Please share an example of the issue you're seeing.

**Comment by romanchekashov** [comment]
You can see bellow highlights. If I remove `const` error disappears.

<img width="1083" alt="Screenshot 2024-01-06 at 12 41 06 AM" src="https://github.com/facebook/stylex/assets/7901859/894b4518-6d43-49fe-af88-62fa1ee43aa3">
<img width="718" alt="Screenshot 2024-01-06 at 12 39 07 AM" src="https://github.com/facebook/stylex/assets/7901859/7d92855f-f482-4bfe-bbe2-dc944ebba526">

**Comment by romanchekashov** [comment]
I thought that `const` cannot be used inside generics `<...>` but maybe this bug related to IntelliJ IDEA 2023.2.2?

**Comment by nmn** [comment]
`const` can be used within generics for functions and classes, but not type aliases.

This feels like an IntelliJ bug. This all works in VS Code. Leaving the issue open for you to verify on your end.

**Comment by daulric** [comment]
> `const` can be used within generics for functions and classes, but not type aliases.
> 
> This feels like an IntelliJ bug. This all works in VS Code. Leaving the issue open for you to verify on your end.

i had that error but I didn't know when I was using VSCode as well. This is an error on Stylex Side

**Comment by daulric** [comment]
this is the error i had 
![Screenshot (93)](https://github.com/facebook/stylex/assets/57965846/6a6729c5-b1f9-46f9-b03f-42d148dd229a)

**Comment by bmg02** [comment]
I'm facing the same error.

**Comment by nmn** [comment]
You're most likely using an old version of Typescript. As you can see on the `nextjs` example in the repo itself, there are no typescript errors.

**Comment by romanchekashov** [comment]
`const` can be used within generics for functions and classes, but not type aliases. - This is a new feature of latest TypeScript 5.3.3 and doesn't work with TS 4.8.8;(

Just upgrade TS version in `package.json` with `"typescript": "^5.3.3"`.

@nmn Please provide example of running jest tests in Nextjs 14 with stylexjs? I've managed a lot to be able to use stylexjs with Next js 14 but I cannot move further with falling tests( I'm using Jest with React Testing Library and getting error:
```
 ● Test suite failed to run

    stylex.defineVars should never be called. It should be compiled away.

      82 | };
      83 |
    > 84 | export const text = stylex.defineVars({
```

**Comment by bmg02** [comment]
Upgrading the typescript solved the issue, thanks.

**Comment by nmn** [comment]
Added a single Jest snapshot test in this repo:

https://github.com/nmn/nextjs-app-dir-stylex
