### ISSUE TITLE
Using explicit return when creating dynamic styles causes an error

### ISSUE THREAD

**Issue by k14lb3** [facebook/stylex#323]
**The problem**

Not omitting the `return` keyword when creating dynamic styles causes a `Styles must be represented as JavaScript objects, not ArrowFunctionExpression` error.

| Synxtax | Type |
| - | - |
| <pre>const styles = stylex.create({<br/>  foo: () => ({ ... }),<br/>});</pre> | ![image](https://github.com/facebook/stylex/assets/76220140/7adba09c-1241-4971-8af2-02d2c9f8b35c) |
| <pre>const styles = stylex.create({<br/>  foo: () => {<br/>    return { ... };<br/>  },<br/>});</pre> | ![image](https://github.com/facebook/stylex/assets/76220140/b155346c-184e-47a9-8c27-42f85997cd99) |

**Expected behavior**

I think they should behave the same since they have the same return type?

**Environment (include versions). Did this work in previous versions?**

```
@stylexjs/stylex@0.4.1
```

**Comment by nedjulius** [comment]
I think it's done so intentionally to reduce the complexity of dynamic styles. Having an explicit return introduces additional complications for the compiler due to the available body of the function.

I might be wrong.

**Comment by nmn** [comment]
@nedjulius is correct. We do not want complex logic within dynamic style functions. Instead the values should be calculated within your component and the final style values should be passed into the function.

Also it's a maintenance burden to compile functions at compile time. We do not use `eval` and any functions used for styles need to be simple enough for us to parse and evaluate statically at compile time.
