### ISSUE TITLE
0.4.1: stylex.inject is not a function

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#334]
**The problem**

0.3.0: working fine
0.4.1: `stylex.inject is not a function`

Either with vite or webpack.

I'm not really sure which information you may need to dig into this.

**Comment by pawelblaszczyk5** [comment]
I guess it’s related to this one and you need to import the `inject` method from different entry point - https://github.com/facebook/stylex/pull/163

**Comment by olivierpascal** [comment]
> I guess it’s related to this one and you need to import the `inject` method from different entry point - #163

I am not even using `inject` in my code.

**Comment by olivierpascal** [comment]
Ok, probably related to https://github.com/HorusGoul/vite-plugin-stylex/issues/29

**Comment by olivierpascal** [comment]
In the meantime, this workaround is working: https://github.com/HorusGoul/vite-plugin-stylex/issues/29#issuecomment-1877511531

Closing.

**Comment by nmn** [comment]
Please try using `0.5.0-alpha.2`. The problem should be fixed as it adds an ESM export for `stylex-inject`.

**Comment by bigfootjon** [comment]
@nmn I just tried updating to 0.5.1 and I'm having this problem with webpack :/

```
Uncaught TypeError: stylex.inject is not a function
...
```

Looking through the stack trace it looks like babel is adding calls to `stylex.inject` which are then broken in webpack. Let me know if I can provide any other debugging info to help

**Comment by nmn** [comment]
@bigfootjon Can you clear all caches. Re-install node_modules and try again? `stylex.inject` hasn't been injected since 0.4.1, so that code appearing at all seems like a caching issue.
