### ISSUE TITLE
Please also add support for attribute injection instead of only CSS properties

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#342]
I know StyleX only supports css properties but is there any hack to make the following code work in a NextJS Image?
```javascript

import Image from "next/image";
import * as stylex from '@stylexjs/stylex';

const DARK_MODE = '@media (prefers-color-scheme: dark)';

const styles = stylex.create({
    logo: {
        src: {
            default: "/svgs/light_theme_logo.svg",
            [DARK_MODE]: "/svgs/dark_theme_logo.svg"
        }
    }
});

const AppLogo = () => {
    return (<Image {...stylex.props(styles.logo)} width={30} height={30} />);
}
export { AppLogo };
```

Such that stylex will supply different src values to the Image depending on whether the app is in dark mode or light mode?

**Comment by nmn** [comment]
> but is there any hack to make the following code work in a NextJS Image?

`src` is not a CSS property, so you can't use StyleX or any CSS library to set it. 
You may be able to use a `<picture>` element or `srcset` to do this. Please ask the NextJS community for help with the Image component to be able to achieve this.

You can do this with StyleX if you use `background-image` on a div or something like that.

-----

@dd-jonas That approach won't work for a server component
