### ISSUE TITLE
The return value of stylex.defineVars() must be bound to a named export

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#348]
**The problem**

```
The return value of stylex.defineVars() must be bound to a named export
```

**How to reproduce**

```ts
import * as stylex from '@stylexjs/stylex';

// works
export const vars = stylex.defineVars({ color: 'red' });

// does not work
const vars = stylex.defineVars({ color: 'red' });
export { vars };
```

I know from the doc that:

> The variable must be exported directly

But the `export { vars }` syntax is generated by rollup, and I don't know if this behavior can be changed through the rollup config.

**Comment by olivierpascal** [comment]
After digging a bit, I'm not sure that the way the typescript transpiler groups named exports can be changed.

**Comment by nmn** [comment]
This is an intentional design decision.

> But the `export { vars }` syntax is generated by rollup

The `.stylex.ts` shouldn't be bundled in the first place. They need to standalone files. Don't use rollup on this file.

**Comment by olivierpascal** [comment]
Yes, I am using `{ preserveModules: true, preserveModulesRoot: 'src' }` so the file structure is preserved and `.stylex.ts` files are standalone. But when they are transpiled from ts to js, exports are always grouped and I still cannot find a way to let them un grouped, but I am still digging.

**Comment by olivierpascal** [comment]
https://github.com/rollup/rollup/discussions/5339#discussioncomment-8121884

Should this issue be reopened then?

**Comment by nmn** [comment]
StyleX can transform TS files, so I don't know why you need to pre-bundle before running StyleX.

**Comment by olivierpascal** [comment]
Sorry, I'm afraid I don't follow you. Do you mean I should not use rollup at all? Or that I should exclude *.stylex.ts' from bundling? How is that possible?

Here is the detailed use-case, to make things crystal clear:

A consumer app (ie. in Next.js) is using a NPM package (ie. '@acme/design-system').

The npm package
- is written in TS and is built with rollup
- `@stylexjs/stylex` is considered as an external package

The consumer app
- has '@acme/design-system' in `nextConfig.transpilePackages`
- `@stylexjs/nextjs-plugin` as dependency and setup in `next.config.js`

The problem: when the npm package is built, *.stylex.ts files are transpiled to `.stylex.js` files, which named exports are not recognized by stylex in the consumer app.

Am I doing something wrong?

**Comment by nmn** [comment]
> Do you mean I should not use rollup at all?

Yes don't do this.

> is written in TS and is built with rollup

Just use  a simple Babel step to strip out types. Don't use Rollup.

-----

The other option is to simply publish the `@acme/design-system` package without any transformation whatsoever. When using StyleX from a NPM package, it is expected that the consumer app will transform the package, so it's not neccessary to transform or bundle it at all.

**Comment by sumanbh** [comment]
@nmn Typically other UI libraries also split their build into CJS and ESM (e.g. mui, mantine etc). Based on what you said, I assume we don't do that for StyleX based component libraries and only publish the ESM build? Or can the StyleX babel plugin transform CJS files as well?

**Comment by nmn** [comment]
@sumanbh Since the UI libraries will get compiled, I would recommend leaving everything in ESM. Only some parts of StyleX work with CJS and even that wouldn't work with compiled out for CJS.

**Comment by olivierpascal** [comment]
So in conclusion, there is no way to use rollup to build the design system package, whether or not me or my company has a good reason to use it.

**Comment by nmn** [comment]
@olivierpascal I'm sure there's a solution to your problem, but I can't say what that might be unless you can help me understand the entire use-case of why you're using Rollup in the first place.

The catch-all solution would be a post-processing step to convert `defineVars` calls back into named exports after rollup is done.

**Comment by steida** [comment]
@olivierpascal bundling belongs to apps, not to libs

**Comment by nikeee** [comment]
React Compiler cannot process libraries in node_modules. So the React Compiler Team recommends running the libs through babel:  https://react.dev/blog/2024/10/21/react-compiler-beta-release

I'm trying to use Vite for that, which uses rollup under the hood. I am now facing the same problem as @olivierpascal. Before that, I just used `tsc`, which worked as expected. Looking at https://github.com/rollup/rollup/discussions/5339, there won't be a solution for rollup in the near future.

**Comment by nmn** [comment]
@nikeee `.stylex.jsx` should work as well. lmk, if you're seeing issues with that.

**Comment by drwpow-figma** [comment]
> The other option is to simply publish the @acme/design-system package without any transformation whatsoever. When using StyleX from a NPM package, it is expected that the consumer app will transform the package, so it's not neccessary to transform or bundle it at all.

We’re also facing the same problems @olivierpascal outlined. Basic npm assumption is ALWAYS transpile the package for consumers. Without it, you have to go through all the motions of telling bundlers to transpile your npm packages but not others. If enough packages did this, it would be unsustainable. There’s a reason all bundlers don’t transpile npm packages by default, and you have to modify default config to opt in.

I think StyleX’s package story could be improved by, say, using a custom extension like `.stylex` (not `.stylex.jsx?`). The “don’t transpile” strategy just doesn’t work in any realistically-sized npm package that also ships normal TS/JS or other React code that does need transpilation. It’s difficult at best, impossible at worst, to try and get some `.js` files transpiling and behaving differently than others loaded from the same npm package. But if the extensions differ, then it’s significantly less burden on consumers—it’s why extensions exist!

I’d also argue that a custom extension also makes the boundaries more clear. As the original issue pointed out, `const vars = stylex.defineVars({ color: 'red' }); export { vars };` is 100% valid JS, functionally identical, and should be supported. Enforcing arbitrary boundaries on how valid JS is composed is difficult. But enforcing boundaries on a custom extension (e.g. `export { vars }` is invalid syntax), is much better for both authors and consumers.

So all that to say I’d like to propose changing to `.stylex` as the default-supported extension so it can be built more efficiently and consumed more efficiently, running it through different transpilation steps.

**Comment by necolas** [comment]
> The “don’t transpile” strategy just doesn’t work in any realistically-sized npm package that also ships normal TS/JS or other React code that does need transpilation.

The recommendation is not "don't transpile", it's don't run the StyleX babel plugin over the code.

**Comment by drwpow-figma** [comment]
> The recommendation is not "don't transpile", it's don't run the StyleX babel plugin over the code.

Ah thanks for clarifying. In that case, could we reopen the issue to support `const vars = stylex.defineVars({ color: 'red' }); export { vars };` then? Import/export resolution and normalization is often a byproduct of transpiling.

**Comment by necolas** [comment]
This issue is 18 months old. Please open a new one if there's something to discuss.

**Comment by mellyeliu** [comment]
@drwpow-figma sorry about the long delay, addressing this issue here https://github.com/facebook/stylex/pull/1372
