### ISSUE TITLE
ESBuild plugin

### ISSUE THREAD

**Issue by randallb** [facebook/stylex#353]
I'm probably going to build an esbuild plugin. I said I'd do it when I was at Meta, but hey, now that I'm not ironically I can probably devote more time to it.

@justicart -- Not sure if you want to play along too. We're not using StyleX yet on boltfoundry.com, but I'm thinking about adding it today. Good use of a vacation day. 😊

If anyone has any requirements or anything, please make it known in this issue.

I couldn't find any other issues that mentioned this, so I'll build it. I'll try to make it compatible with Node.JS, but I'm using Deno, so it might not be.

Do you want this to be a community plugin or in the monorepo?

**Comment by nucleartux** [comment]
I think it's already merged to beta branch https://github.com/facebook/stylex/commit/c91b2352d9135c0e65e3a5495cc6e75310bd7438

**Comment by zaydek** [comment]
@nmn Just wanted to chime in. I switched from Vite to esbuild using the StyleX esbuild plugin on a pretty significantly sized code base and I haven't had any problems, it's been great. Thank you!
