### ISSUE TITLE
I am getting a TypeError coninously for each update in any file.

### ISSUE THREAD

**Issue by Thivakar-N** [facebook/stylex#359]
![image](https://github.com/facebook/stylex/assets/125954538/6e1d20c0-ec55-4031-a1d6-08b0b383545d)

I am getting above error in my NextJs app. I am having V14.0.4 and configs are done based on your docs. Page needs a refresh to get rid of the error. Can you please explain why is it?

**Comment by necolas** [comment]
There's not enough information in your post to understand if the problem you're experiencing is even caused by StyleX. Please read the issue template to provide the information that helps us triage issues effectively

**Comment by Thivakar-N** [comment]
My .babelrc.js file >>
module.exports = {
  presets: ["next/babel"],
  plugins: [
    [
      "@stylexjs/babel-plugin",
      {
        dev: process.env.NODE_ENV === "development",
        runtimeInjection: false,
        genConditionalClasses: true,
        treeshakeCompensation: true,
        unstable_moduleResolution: {
          type: "commonJS",
          rootDir: __dirname,
        },
      },
    ],
  ],
};

My next.config.js file >>>
/** @type {import('next').NextConfig} */
const stylexPlugin = require("@stylexjs/nextjs-plugin");
const babelrc = require("./.babelrc.js");
const plugins = babelrc.plugins;
const [_name, options] = plugins.find(
  (plugin) => Array.isArray(plugin) && plugin[0] === "@stylexjs/babel-plugin"
);
const rootDir = options.unstable_moduleResolution.rootDir ?? __dirname;

module.exports = stylexPlugin({
  rootDir,
  useCSSLayers: true,
})({
  transpilePackages: ["@stylexjs/open-props"],
});

I  am getting the error message whenevent I modify something in my main tsx coponents. If disapeears only after refreshing the page again.

**Comment by nmn** [comment]
Remove this line: `runtimeInjection: false,` from your `babelrc`

**Comment by Thivakar-N** [comment]
Thank you so much. It is working now
