### ISSUE TITLE
[feat]: Footer alignment

### ISSUE THREAD

**Issue by dakshsinghrathore** [facebook/stylex#37]
**Is your feature request related to a problem? Please describe.**
The alignment of the footer isn't at the center.

![image](https://github.com/facebook/stylex/assets/115932772/b0e50fa4-4267-4d7e-82fd-d9d97dd88d96)

**Describe a solution you'd like**
Will fix the alignment of the footer to the center

![image](https://github.com/facebook/stylex/assets/115932772/c47cbd0a-789c-48d0-9421-6bf12ce0f83d)

**Describe alternatives you've considered**

NULL

**Additional context**

NULL

**Comment by necolas** [comment]
The left-side text alignment within each column makes it look left-skewed, but the footer itself is centered

<img width="1715" alt="image" src="https://github.com/facebook/stylex/assets/239676/0d2ffc00-2684-4bde-b1de-f51547929d5d">
