### ISSUE TITLE
lineHeight: "42px" not valid

### ISSUE THREAD

**Issue by steida** [facebook/stylex#383]
### Describe the issue

 Types of property 'lineHeight' are incompatible.
      Type 'StyleXClassNameFor<"lineHeight", "42px">' is not assignable to type 'StyleXClassNameFor<"lineHeight", Readonly<number | "initial" | "inherit" | "unset" | null | undefined>>'.

### Expected behavior

It should work, or is there any reason why it should not?

### Steps to reproduce

Define a style with lineHeight: "42px",

**Comment by yousoumar** [comment]
Hi @steida! I created this [PR](https://github.com/facebook/stylex/pull/384) to solve the issue. Same issue as #356.
