### ISSUE TITLE
stylex.include not working in 0.5.x

### ISSUE THREAD

**Issue by zaydek** [facebook/stylex#394]
### Describe the issue

In a previous version of Stylex (`^0.4.1`), I was able to do something like the following:

<img width="751" alt="Screenshot 2024-01-27 at 6 20 28 PM" src="https://github.com/facebook/stylex/assets/58870766/2985e14f-c72d-4ffe-a059-f824ff3ee796">

The pattern I was specifically interested in is the following:

```
	primary: {
		...stylex.include(typography.paragraph),
		alignItems: "center",
		backgroundColor: "rgb(255, 255, 255, 0.0625)",
		borderRadius: 1e3,
		boxShadow: "0 0 0 1px rgb(255, 255, 255, 0.0625)",
		color: "rgb(255, 255, 255, 0.25)",
		display: "flex",
		fontWeight: 600,
		justifyContent: "center",
		paddingBlock: 12,
		paddingInline: 16,
	},
```

So I could inline the typography and simply use `stylex.stylex(styles.button)` instead of `stylex.props(styles.button, typography.paragraph, ...)`. In order for this to work, I needed to use the since deprecated API `stylex.stylex` so it appears this behavior is no longer suported.

By looking at https://github.com/facebook/stylex/issues/136 I can see that the API for include itself is intentionally undocumented so as to see if the community really needs this feature.

In `^5.0.8` it looks like the feature is not supported at all. Here's a repro: https://github.com/zaydek/experimental-vite-stylex-eslint. (I am simply trying to compose a `center` style, more or less the same use case.)

My use case is for things like compound utiltiies (e.g. typography, centering, text truncation, etc.) I want to be able to inline these styles in the stylesheet API so it's colocated. The other benefit of this approach is that when I implement the styles, I can easily add conditional variants such as `stylex.props(styles.input, isError && ...)` instead of something like this `stylex.props(styles.typography, typography.isCenter, styles.input, styles.isError && ...)`. The other small benefit is that it's slightly easier to annotate using comments using the stylesheet API, because it's tall text rather than wide text.

### Expected behavior

I'd like to be able to use stylex.include if it's still supported because colocation is good and it makes for less verbose code and it's easier to annotate with comments.

### Steps to reproduce

Repro is here https://github.com/zaydek/experimental-vite-stylex-eslint. This demonstrates that the feature doesn't work.

**Comment by zaydek** [comment]
To be clear it's fine if this feature is planned to be deprecated I just want to understand whether `include` plans to be supported at all and if not, does `stylex.include` introduce any technical ambiguity such that it's not worth it?

**Comment by nmn** [comment]
A question: I see you mention v `5.0.8` a couple of times and I'm not sure where that is coming from?

----

I think I know where the issue is coming from. An optimisation I introduced to minimise the amount of code generated after compilation will remove the `stylex.create` calls entirely when all the styles are used locally. As a quick workaround, throwing an `export` before the `const` should fix the problem for now!

I'll fix the bug for the next release.

**Comment by zaydek** [comment]
Thanks @nmn! Yes `5.0.8` is absolutely a typo, it should be `0.5.1`, the recently released version.

> I think I know where the issue is coming from. An optimisation I introduced to minimise the amount of code generated after compilation will remove the `stylex.create` calls entirely when all the styles are used locally. As a quick workaround, throwing an `export` before the `const` should fix the problem for now!

I think we're on the same page. Basically I haven't been able to use `stylex.include` in `0.5.1` but I will try using `export` for now to see if that works. In my example and the linked repo, you're correct that it was colocated in the same file and that might be why I was having trouble validating if `stylex.include` works at all in `0.5.1`.

> 1. `stylex.stylex` Why do you need this? It breaks dynamic styles. If you're not using React we even introduced `stylex.attrs` which sets `class` instead of `className`.

I'll admit that my use of `className` and `stylex.stylex` were simply experiments in non production code bases where I was trying anything to make `stylex.include` work becauase I was interested to see what it feels like to author that kind of code.

> 2. Your usage of `:is` and pseudo classes at the top-level is definitely _NOT_ supported and will break in future releases.
> 
> `styles.secondary` should be written as:
> 
> ```tsx
> secondary: {
>   ...stylex.include(typography.label),
>   color: {
>     default: 'rgb(255, 255, 255, 0.875)',
>     ':hover': 'rgb(255,255,255)',
>     ':focus-within': 'rgb(255,255,255)',
>   },
>   fontWeight: 500,
>   textAlign: 'center',
>   textDecoration: {
>     default: 'none',
>     ':hover': 'underline',
>     ':focus-within': 'underline',
>   },
> }

Thanks, I just realized yesterday that I've probably been authoring styles wrong this whole time. But it's no big deal -- the refactor would simply involve me moving things around in the existing `stylex.create` calls, I'll definitely correct this going forwards.

> Now, it's possible you're trying to _merge_ the values of `textDecoration` from `typography.label` and not replace them. This is exactly what we don't want to allow as it can cause unpredictability. (The generated styles are literally not in the right order for this to work consistently). If you want this pattern, set a variable in `typography.label` as well.

Yeah so my interest was in _can I merge styles from a previous stylesheet class declaration so that I can reuse patterns_, typography being an example of this use case.

> ```tsx
> // typography.label
> [vars.textDecoration]: 'none',
> ```
> 
> And then you can use that variable in `styles.secondary`:
> 
> ```tsx
> secondary: {
>   ...
>   textDecoration: {
>     default: vars.textDecoration,
>     ':hover': 'underline',
>     ':focus-within': 'underline',
>   },
> }
> ```

Oh… thank you. You exposed me to a new idea -- I know how to set CSS variables using `defineVars` in stylex but  I didn't realize I can also use `[vars.variableName]` as a way to set them. OK that's really good to know.

> I know some of this probably feels like too much work to you and I'm working on some tools to make things more convenient. But all of these rules have been though out to enable consistent merging of styles. If you break these rules you'll get at least some amount of ambiguity in style merging.

No worries I get it. You're basically in a position where you and your team need to unravel decades of thinking in CSS, which could arguably be considered harmful because while CSS reads relatively straightforward, working out what are the computed styles are non trivial and sometimes requires heavy machinery (by the end user) like Cascade Layers just to get thinks to behave. So I'm really open minded when it comes to learning and picking up safer ways to write CSS (ala Stylex), provided that I will need to do some unlearning as well.

From what I gather:

1. Only use ever use `stylex.create` and `stylex.props` or `stylex.attrs` (for non React), that's really fundamental and anything else is suspect to breakage.
2. With respect to authoring pseudos, styles need to be partitioned by property not by class, meaning `color: { default: ..., "<pseudo>": ... }` is the only correct syntax.
3. If using `stylex.include`, lean on CSS variables because ordering may not work as expected. You can also use `[vars.x]` syntax. And if you really want to compose multiple CSS classes, use `style.create` like `stylex.props(a, b, c, d && e, condition ? f : g)`.

---

> (The generated styles are literally not in the right order for this to work consistently)

The one remaining question I have is can the position of where `stylex.include` is called be used to resolve the ordering issues you mention?

For example:

```js
 1 const foo = stylex.create({
 2   foo: {
 3     // ...
 4   },
 5 })
 6 const bar = stylex.create({
 7   bar: {
 8     // ...
 9     ...stylex.include(foo.foo),
10     // ...
11   },
12 })

stylex.props(bar.bar)
```

We can see that `stylex.include` is invoked at line 9, which in theory would be equivalent to:

```js
const foo = stylex.create({
  foo: {
    // ...
  },
})
const bar1 = stylex.create({
  bar1: {
    // ...
  },
})
const bar2 = stylex.create({
  bar2: {
    // ...
  },
})

stylex.props(bar1.bar1, foo.foo, bar2.bar2)
```

If it's possible, I much prefer the first API, `stylex.props(bar.bar)`, because I don't need to additionally remember the order in which to invoke the classes. I simply use the self contained atom that is `stylex.props(bar.bar)` rather than something like `stylex.props(bar1.bar1, foo.foo, bar2.bar2)` which is confusing because I need to alternate between `bar1` and `bar2` and `foo`.

**Comment by nmn** [comment]
> If using `stylex.include`, lean on CSS variables because ordering may not work as expected.

You can definitely still use regular properties when using `stylex.include`. The simple takeaway is that don't try to merge values under different conditions for the same property (`textDecoration`). The last value given to `textDecoration` (as a whole) wins.

The variable workaround is to achieve that pattern if you really need it. (Although we don't think it's a good pattern in general as it creates more coupling between unrelated styles).

-----

You question about using `stylex.include` is correct. As `stylex.include` is under evaluation, I will take this as a vote for making it an official API. If the `export` trick works, you can continue using `stylex.include`. I will try and fix the bugs soon.

**Comment by zaydek** [comment]
@nmn Thanks! I wanted to follow up since I tried the export trick you mentioned but using:

```
"@stylexjs/babel-plugin": "^0.5.1",
"@stylexjs/eslint-plugin": "^0.5.1",
"vite": "^5.0.8",
"vite-plugin-stylex-dev": "^0.2.5"
```

I still can't get spread to work. I did try exporting everything but to no avail. I believe you only meant that `center` in this case needed to be exported but I exported everything to be certain. Here's the snippet for reference:

```tsx
import * as stylex from "@stylexjs/stylex"

export const center = stylex.create({
  center: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
  },
})

export const styles = stylex.create({
  container: {
    ...stylex.include(center.center),
    blockSize: "100vh",
  },
  button: {
    alignItems: "center",
    backgroundColor: {
      default: "blue",
      ":hover": "orange",
      ":active": "red",
    },
    display: "flex",
    gap: 8,
    padding: 16,
    borderRadius: 14,
    color: {
      default: "gray",
      ":hover": "white",
    },
  },
  icon: {
    blockSize: 16,
    inlineSize: 16,
  },
})

export function CentralCamera4FilledOffStroke2Radius2(props: JSX.IntrinsicElements["svg"]) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M21 17V7C21 5.89543 20.1046 5 19 5H10.0858C9.71071 5 9.351 4.851 9.08579 4.58579C8.71071 4.21071 8.20201 4 7.67157 4H6.32843C5.79799 4 5.28929 4.21071 4.91421 4.58579L4.5 5.06301C3.63739 5.28503 3 6.06808 3 7V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17Z" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" />
      <path d="M17 12C17 13.6569 15.6569 15 14 15C12.3431 15 11 13.6569 11 12C11 10.3431 12.3431 9 14 9C15.6569 9 17 10.3431 17 12Z" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" />
      <path d="M7 9H7.01" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

export function App() {
  return (
    <div {...stylex.props(styles.container)}>
      <div {...stylex.props(styles.button)}>
        <CentralCamera4FilledOffStroke2Radius2 {...stylex.props(styles.icon)} />
        <div>Hello, World!</div>
      </div>
    </div>
  )
}
```

Just let me know if I'm doing something wrong. Here's the repro for reference: https://github.com/zaydek/experimental-vite-stylex-eslint/blob/main/src/App.tsx.

> You question about using `stylex.include` is correct. As `stylex.include` is under evaluation, I will take this as a vote for making it an official API. If the `export` trick works, you can continue using `stylex.include`. I will try and fix the bugs soon.

My inclination is that `stylex.include` can help a lot with nuances like void elements such as `<input>` where you can't simply use a typographic component like `<Heading>`, `<Paragraph>` and you have to merge styles. This comes up in other places but for the time being I like the idea that there's a back door for these edge cases where it'd be really nice to colocate logic in one place. With more experience I may change my mind but at present I'd just like to experiment more.

Looking forward to a fix if that's necessary. Happy to report if any future fixes work.

**Comment by zaydek** [comment]
<img width="623" alt="Screenshot 2024-01-28 at 8 52 15 PM" src="https://github.com/facebook/stylex/assets/58870766/e46013be-0b2d-4e09-ab69-147d8af86a60">

Oh I forogt to mention I noticed this terminal log. I don't know if it's related but I believe it only started appearing once I tried to use stylex.include in this way.

**Comment by nmn** [comment]
@zaydek I just put up a PR with the fix to this problem. The `export` workaround looked like it would work, but it only solved half the problem.

While you wait, here's an actual workaround that will definitely work:

Import a variable from an external module with a `null` value and use it within your `stylex.props` calls.

```tsx
stylex.props(importedNull, styles.container, styles.center, ...)
```

This "unknown" value will cause the StyleX optimization to bail out and everything should start working correctly.

**Comment by zaydek** [comment]
@nmn Thanks can confirm `importedNull` works. Haha thanks. 😈

**Comment by zaydek** [comment]
@nmn For what it's worth it looks like I can simply use stylex.props(null, ...) and triggers the deoptimization all the same.

**Comment by nmn** [comment]
> For what it's worth it looks like I can simply use stylex.props(null, ...) and triggers the deoptimization all the same.

This is incidental and may not be the case in the future.

**Comment by predaytor** [comment]
It is interesting that this issue still appears:
```bash
styleq: __included_414__ typeof [object Object] is not 'string' or 'null'.
```
Using `stylex.props(null, ...)` solves the problem that styles are not applied.

Personally, I find `stylex.include` a very useful API. Does using this trigger serious deoptimization? Is it better to rely on `stylex.props` instead?

**Comment by necolas** [comment]
```
styleq: __included_414__ typeof [object Object] is not 'string' or 'null'.
```

This error comes from here:

https://github.com/necolas/styleq/blob/main/src/styleq.js#L107-L114

It's telling you that the value of a key in the compiled data is not a string, which suggests the source code (in this case I'm assuming it's an `include` call) is either not compiled or is being compiled to an incorrect format.

**Comment by predaytor** [comment]
yes, it's not a big problem, just a readability issue in rare cases. But it's very useful for creating variants where the composition appears, instead of conditional propagation based on the exact variant via `stylex.props`.
```tsx

export type ButtonVariants = {
	variant: keyof typeof variants;
	size: keyof typeof sizes;
};

export type ButtonProps = WithStyleX<AriaButtonProps> & ButtonVariants;

export function Button({ variant, size, style, ...props }: ButtonProps) {
	return <AriaButton {...props} {...stylex.props(styles.base, sizes[size], variants[variant], style)} />;
}

export const styles = stylex.create({
	base: {
		// ...
	},
});

export const variants = stylex.create({
	primary: {
		// ...
	},

	ghostHigh: {
		...stylex.include($text.weights.regular),
		// ...
	},
});

export const sizes = stylex.create({
	sm: {
		...stylex.include($text.variants.textXs),
		...stylex.include($text.weights.medium),
		padding: `${$sizes.spacing2} ${$sizes.spacing3}`,
	},

	// ...
});

```

**Comment by necolas** [comment]
I don't really understand what you're trying to show in that code example. Why is `sizes` used within `sizes`? Where is `$text` coming from?

**Comment by predaytor** [comment]
Sorry for the confusion, `$sizes`, `$text` are just aliased token imports to avoid namespace conflict. I have updated the comment above.

**Comment by necolas** [comment]
It's still not clear to me? But you can use `[a, b]` for style composition without ever having to use `includes`. That will produce smaller bundles (no duplication of declarations in the compiled output), probably have marginally faster runtime merging, and can avoid whatever bugs currently exist with the `includes` implementation.

**Comment by predaytor** [comment]
yes, it was more of a compositional preference. will do simply with `stylex.props`.

**Comment by predaytor** [comment]
Found that `stylex.include` always works as intended when included in conditional styles, and throws an error when used with regular styles (since it's easier to just use `stylex.props` directly on the element). So I don't think there's a bug at all. I'd like to see this feature stay and have its place in the docs. Thx.

**Comment by olivierpascal** [comment]
Is this bug fixed? I still need to use the null workaround `<div {...stylex.props(null, myStyles.xxx)} />` if `myStyles.xxx` is using `{ ...stylex.include(...), ... }`.

**Comment by necolas** [comment]
You can not use includes instead. The API is likely to be removed and it is not used internally

**Comment by piotrblasiak** [comment]
Seems like stylex.include was removed in 0.11? Is there any replacement? :(
