### ISSUE TITLE
Spacings seem to have typos?

### ISSUE THREAD

**Issue by cly** [facebook/stylex#405]
https://github.com/facebook/stylex/blob/9b3db10a6f4c5cdb315a90974db1a7f91c842bd6/packages/open-props/src/sizes.stylex.js#L117

Based on https://github.com/argyleink/open-props/blob/main/src/props.sizes.css

These should probably be
```
xxs: "240px",
xs: "360px",
...
```

**Comment by nmn** [comment]
Good catch! I don't know how this slipped through.
