### ISSUE TITLE
autofix for @stylexjs/sort-keys

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#415]
### Describe the feature request

I don't know exactly how eslint plugins work, but is it possible to autofix keys order with `eslint --fix file.stylex.ts`?

**Comment by nedjulius** [comment]
currently it's not supported

**Comment by nedjulius** [comment]
> @nmn I think sorting should be implemented as the Prettier plugin. It should be done on file save; developers should not be forced to think about that. Also, the alphabetical sort is DX suboptimal, imho.
> 
> 
> 
> https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

Formatting on save is a feature that depends on individual developer's setup. I would argue that key ordering is more of a code standard than a formatting issue and is definitely appropriate as an ESLint rule. That doesn't mean that a prettier plugin can't exist though.

**Comment by nmn** [comment]
@nedjulius You have my "blessing" to implement the auto-fix for the ESLint rule.

@steida I'm not opposed to a prettier plugin either, but the goal is for StyleX to never require any particular sorting like Tailwind does. And so I don't want to build the Prettier plugin to soon which gives the impression that the ordering is required.

**Comment by nedjulius** [comment]
@nmn amen. will work on this

**Comment by nedjulius** [comment]
fyi @steida , @olivierpascal I just released a prettier plugin that does the same thing: https://github.com/nedjulius/prettier-plugin-stylex-key-sort
