### ISSUE TITLE
Allow undefined where null is allowed

### ISSUE THREAD

**Issue by steida** [facebook/stylex#417]
### Describe the feature request

Is there a reason why `undefined` isn't supported? My component has optional `titleStyle`, so it can be undefined. 

Now I have to convert undefined to false `titleStyle != null`

```tsx
<Text
  style={[
    styles.title,
    styles[variant],
    titleStyle != null && titleStyle,
    hovered && styles.titleHover,
    pressed && styles.titlePressed,
  ]}
>
  {title}
</Text>
```

**Comment by nmn** [comment]
undefined *should* be supported when used there. I'll look into it.

**Comment by steida** [comment]
@nmn Maybe it's because of exactOptionalPropertyTypes

https://github.com/Effect-TS/effect/tree/main/packages/schema#requirements

**Comment by nmn** [comment]
Thanks for catching this. Put up a PR with the fix.
