### ISSUE TITLE
@stylexjs/eslint-plugin: Support variable font weight

### ISSUE THREAD

**Issue by robinlahtinen** [facebook/stylex#419]
### Describe the issue

Stylex ESLint forces predetermined font weights, but [variable fonts support any number from 1 to 1000](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/Variable_fonts_guide#weight).

### Expected behavior

Stylex ESLint accepts any value for font weight, ex. 625.

### Steps to reproduce

1. Create a style with fontWeight property
2. Use value outside the type, for example 625 or 850.
3. Try linter

### Test case

```tsx
const styles = stylex.create({
    example: {
        fontWeight: 625,
    },
});
```

**Comment by yousoumar** [comment]
Hi @robinlahtinen, you are right. This is repeated [here as well](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#number). @nmn I want to work on this if there is no argument on why we should only have these predetermined numbers (I understand why the string ones such as `normal` and `bold` are fixed).
