### ISSUE TITLE
Issue with stylex.create() in Vite Project Using @stylexjs/stylex

### ISSUE THREAD

**Issue by GensIto** [facebook/stylex#426]
### Describe the feature request

Hello,

I am currently working on creating a custom UI library using @stylexjs/stylex in a Vite project. However, I am encountering an issue when trying to use values defined with stylex.defineVars in stylex.create().

Here's the error message I receive during the build process:

```
✓ 5 modules transformed.
[vite-plugin-stylex] /privateWorkspace/vite-react/src/components/Button/styles.ts: Only static values are allowed inside of a stylex.create() call.
file: /Users/itougenta/Desktop/workspace/privateWorkspace/vite-react/src/components/Button/styles.ts
error during build:
This error suggests that only static values are allowed inside of a stylex.create() call. However, I am using values that I've defined with stylex.defineVars, and I expected them to be treated as static.
```

Could you please help me understand why this issue is occurring and suggest any possible solutions? I've double-checked my setup and code, but I can't seem to resolve this issue.

Thank you for your assistance.

Best regards,

**Comment by GensIto** [comment]
@olivierpascal 
thanks
I used src/styles/color.stylex.ts
```
import stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  primary: "black",
  secondary: "#333",
  accent: "blue",
  white: "white",
  black: "black",
  gray: "#333",
  lightGray: "#666",
  darkGray: "#222",
  red: "red",
  green: "green",
});
```
src/ui/Button.tsx
```
import stylex from "@stylexjs/stylex";
import { colors } from "@/styles/color.stylex";

export const styles = stylex.create({
  button: {
    color: colors.white,
    fontSize: "1rem",
    padding: "1rem",
    backgroundColor: "black",
    border: "none",
    borderRadius: "0.25rem",
    cursor: "pointer",
    filter: {
      default: "drop-shadow(0 0 2em #646cffaa)",
      ":hover": "drop-shadow(0 0 2em #61dafbaa)",
    },
  },
});
```
errors occur when used in this way

**Comment by nmn** [comment]
The problem is that you're using an alias to import the variables. Replace `"@/styles/color.stylex";` with a relative and import to fix the problem.

You should also be able to configure StyleX with the `aliases` option to resolve these aliases for you. For now, the configuration needs absolute file paths. See the nextjs example in the repo for an example of how to do this.

**Comment by olivierpascal** [comment]
I think you should use the `aliases` option of stylex:

```js
styleX({
  aliases: {
    '@/*': [path.join(__dirname, 'src', '*')],
  },
})
```

https://github.com/facebook/stylex/blob/c97421056c819f042271d717eee8ce5c1a4c1669/apps/docs/docs/api/configuration/babel-plugin.mdx#L127
