### ISSUE TITLE
Does / Will StyleX support React Native / Metro? 

### ISSUE THREAD

**Issue by alpheustangs** [facebook/stylex#430]
### Describe the feature request

Since React Native uses Metro for bundling, does / will StyleX support React Native? If so, how do I set up StyleX for React Native?

**Comment by necolas** [comment]
Our solution for using StyleX on native is now open source: https://github.com/facebook/react-strict-dom

**Comment by drager** [comment]
> Our solution for using StyleX on native is now open source: https://github.com/facebook/react-strict-dom

So StyleX works with that for React Native? If it does, I see it is experimental right now. Is there any timeline for making it stable? And, are you using it for your production apps for native right now?
