### ISSUE TITLE
ESM & CJS support for Rollup Plugin

### ISSUE THREAD

**Issue by VojGin** [facebook/stylex#451]
### Describe the feature request

StyleX (all of the packages, including plugins) is written and build as ES Module. So it can be easily imported to any ESM compatible project. But not all of the packages have support for CommonJS and it's currently impossible to import it into a CJS project. Can we have also CJS build support for all packages?

To give you an example. NX rollup executor configuration currently does not support ESM. This means StyleX currently can't be used in NX monorepo projects using rollup builder. (See [this](https://github.com/nrwl/nx/issues/8459)). The reason is that `stylexjs/rollup-plugin` does not support cjs.

**Comment by nmn** [comment]
The `stylex` package already has both ESM and CJS exports. The build script generates both variants of the package and the `package.json` has been configured to support both kinds of module systems. There is likely an issue with your Nx configuration as Rollup likes to import ESM when possible.

That is the only package that needs to be bundled as every other package is a plugin for Babel, ESLint or some bundler.

**Comment by VojGin** [comment]
@nmn Thanks for the reply. I probably expressed myself incorrenctly.

What you are saying is true. The stylex package indeed supports both esm and cjs.

But in my original post I mention `(all of the packages)`. Meaning all of the monorepo packages such as plugins. For example the `rollup-plugin` does not support cjs. And that's the issue I'm trying to raise here.

**Comment by nmn** [comment]
My understanding was that Rollup was all-in on ESM, so only exporting an ESM build was intentional. This is also the case for the Babel and ESlint plugins which need to be CJS to work.

We can probably add CJS support the rollup plugin without too much trouble.

**Comment by VojGin** [comment]
That would be brilliant. I don’t think the support for cjs should bring any hassle in the long run. Although we may hopefully see a future with single united module philosophy. 🙂

**Comment by VojGin** [comment]
Hey @nmn, is the support planned on any roadmap? Can I help with this anyhow? Thanks! 🙏

**Comment by nmn** [comment]
@VojGin Happy to accept a PR as I haven't had the time to prioritize this yet. The `@stylexjs/stylex` package is a good example to use.

**Comment by Luko248** [comment]
This is exactly what we currently need on our project. What is blocking this merge request please?
