### ISSUE TITLE
Add types for the @stylexjs/rollup-plugin package

### ISSUE THREAD

**Issue by HorusGoul** [facebook/stylex#46]
**Is your feature request related to a problem? Please describe.**
The current implementation of the Rollup plugin doesn't use Flow as other packages like `@stylexjs/babel-plugin`, so it doesn't include TypeScript or Flow type definitions.

**Describe a solution you'd like**
Type the package.

**Describe alternatives you've considered**
An alternative would be to publish the typings to DefinitelyTyped, but that doesn't feel right since this project ships type definitions for other packages.

**Additional context**
\-

---

I'm open to creating a PR about this, but I've never used Flow before so I need to take a look at the docs first lol.

**Comment by nmn** [comment]
I'm already working on this!

**Comment by kevintyj** [comment]
It seems that it already generates a types file, adding the types to package.json and initially testing it seems to function as indented.

**Comment by nmn** [comment]
Merged.
