### ISSUE TITLE
I would like to support dev-runtime for Next14

### ISSUE THREAD

**Issue by watanabeyu** [facebook/stylex#470]
### Describe the feature request

In Next14, even when setting runtimeInjection to true in .babelrc, the CSS does not update during development.
I believe StyleX is an excellent zero-runtime CSS library, so I really hope there can be some solution for support in Next14.
I understand the issue with the swc compiler, but I would like to use it for development.

**Comment by nmn** [comment]
If you're using the `app` directory with Next 14 you're using Server Components. Server Components are not compatible with any runtime injection of styles.

`dev-runtime` will never be supported with Next 14. In fact `dev-runtime` isn't meant for development at all. It *only* exists for quick prototyping before setting up a proper build setup.

We have an example Next 14 app in the repo and another starter project linked on the [Ecosystem page](https://stylexjs.com/docs/learn/ecosystem/#starter-templates).

We know that the hot-reloading with Next is sub-par and we're working on a CLI (#412)  to solve this problem.
