### ISSUE TITLE
ESLint rule `sort-keys` incorrectly sorts pseudo-classes above parent properties

### ISSUE THREAD

**Issue by VersorVerbi** [facebook/stylex#472]
### Describe the issue

When using the `@stylexjs/sort-keys` rule, it incorrectly objects to the [pseudo-class](https://stylexjs.com/docs/learn/styling-ui/defining-styles/#pseudo-classes) structure on the basis that `default` should sort above the parent property.

### Expected behavior

Properties within objects assigned to CSS properties should not be sorted into the parent list of CSS properties.

### Steps to reproduce

1. Create a style using StyleX that uses pseudo-classes (or media queries) on a property that sorts alphabetically after `default`, e.g., `textDecoration`. Make sure to have at least one other property in that style object.
2. Run ESLint using the `@stylexjs/sort-keys` rule.

### Test case

```typescript
const styles = stylex.create({
  link: {
    color: 'red',
    textDecoration: {
      default: 'none',
      ':hover': 'underline'
    }
  }
});
```

**Comment by nedjulius** [comment]
hi @VersorVerbi can you also provide the version of `@stylexjs/sort-keys`?

if I understand your problem correctly, it might have [been fixed in the past](https://github.com/facebook/stylex/pull/392/files). I tried running your test case locally and did not encounter any issues.

**Comment by VersorVerbi** [comment]
I have version 0.5.1 of `@stylexjs/eslint-plugin`. Has there been another release already?

**Comment by nedjulius** [comment]
no, that is the latest version you are using.

to understand your problem correctly, in the example test case that you provided, you are getting a suggestion that `default` key should be above `textDecoration`?

**Comment by VersorVerbi** [comment]
Looks like you have to have at least one more property in the object. Updated the issue above with a clearer example.

**Comment by nedjulius** [comment]
hmm weird, I still can't reproduce it. do you have multiple `stylex.create` calls in that file?

**Comment by VersorVerbi** [comment]
Tried on a couple different machines to make sure it wasn't one particular OS/IDE setup. [Here](https://github.com/VersorVerbi/minimum-reproducible-stylex-bug)'s a minimum-reproducible repo.

```console
user@machine:~/Documents/GitHub/minimum-reproducible-stylex-bug$ npx eslint .
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .

/home/user/Documents/GitHub/minimum-reproducible-stylex-bug/src/App.js
  9:7  warning  StyleX property key "default" should be above "textDecoration"  @stylexjs/sort-keys

/home/user/Documents/GitHub/minimum-reproducible-stylex-bug/src/App.test.js
  4:1   error  'test' is not defined                    no-undef
  5:10  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
  7:3   error  'expect' is not defined                  no-undef

✖ 4 problems (3 errors, 1 warning)
```

**Comment by nedjulius** [comment]
thank you for providing the reproducible code. I was trying to repro on the main branch example module using the latest build of the plugin. I checked the source code of the latest published version and it seems that the bug that I referenced above is not yet published. you will probably have to wait till next major release for this bug to be fixed.

**Comment by VersorVerbi** [comment]
Works for me. I just wanted to make sure it was on the radar and didn't see an existing issue for it.

Feel free to close this issue per your normal process!

**Comment by VersorVerbi** [comment]
Confirmed, works as expected now.
