### ISSUE TITLE
RFC: esbuild plugin

### ISSUE THREAD

**Issue by randallb** [facebook/stylex#486]
### Describe the feature request

I'm planning to build out an esbuild plugin... going to use this issue to track progress, etc. @nmn any needs or requests?

**Comment by nedjulius** [comment]
hey, an esbuild plugin already exists (unless you intend to do something else): https://github.com/facebook/stylex/tree/main/packages/esbuild-plugin

**Comment by nmn** [comment]
Yeah, anything wrong with the current ESBuild plugin? Happy to accept any fixes.
