### ISSUE TITLE
Add ability to customise class names generation so we can use one letter classnames.

### ISSUE THREAD

**Issue by igoryusha22** [facebook/stylex#493]
### Describe the feature request

Please give us a small sizes for class names as it was introduced from the beginning.

![image](https://github.com/facebook/stylex/assets/56885648/05c9eec4-2000-4996-9cca-eee13966e15c)

**Comment by necolas** [comment]
The current class names are deterministic (ie stable) and don't clash with any other potential styling systems, which makes them safer and easier to scale than having a sequential or iterative naming method

**Comment by igoryusha22** [comment]
@necolas but it less performant compare to one letter classnames, is not it?

**Comment by necolas** [comment]
There is no significant difference in performance. Even if it were, performance at the cost of reliability is the wrong trade off

**Comment by igoryusha22** [comment]
@necolas hm. Could not you please expand your point of view about reliability? What's wrong with sequential or iterative naming methods?

**Comment by nmn** [comment]
> What's wrong with sequential or iterative naming methods?

This kind of approach makes caching impossible. If you don't compile in the same order, you get different results. You can't do partial compiles. You can't do hot-reloading. etc. etc.
