### ISSUE TITLE
[@styles/open-props]: Has any plan/progress to support `ESM`?

### ISSUE THREAD

**Issue by eryue0220** [facebook/stylex#505]
## Describe the feature request

Recently, I am trying to support astro in [unplugin-stylex](https://github.com/eryue0220/unplugin-stylex), but the `@stylexjs/open-props` didn't support ESM Module.  So is there any plan or progress to upgrade the package `@stylesjs/open-props` to support ESM Module? If no, I'd like to try.

**Comment by nmn** [comment]
`@stylexjs/open-props` is published as ESM. What do you mean?

**Comment by eryue0220** [comment]
Yes but there is one more thing to do:

* set `type: "module"` in the `package.json`;
* add `.mjs` extension when building the lib;

Or it will occur an error like this:
![image](https://github.com/facebook/stylex/assets/3050418/8033d635-d764-465a-9a14-2e63e3d3e3ca)

The example code is [here](https://github.com/eryue0220/unplugin-stylex/blob/feat/support-astro/examples/astro-example)
