### ISSUE TITLE
How can I use container queries with StyleX?

### ISSUE THREAD

**Issue by nexisbs** [facebook/stylex#515]
Hi, I'm trying to use container queries (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) with styleX, but it not seems to work at all.

Can you add a support for them?

**Comment by nmn** [comment]
Container queries are fully supported.

You have to set `containerType: "inline-size"` on a container, and then you can use `@container` queries [just like `@media` queries](https://stylexjs.com/docs/learn/styling-ui/defining-styles/#media-queries-and-other--rules) on a child element.

If something is not working as expected, please provide an example of what is not working. Ideally with a small project (perhaps on StackBlitz?) that shows the error.
