### ISSUE TITLE
Nested pseudo classes within pseudo elements

### ISSUE THREAD

**Issue by larsfoll** [facebook/stylex#550]
### Describe the issue

According to the @stylexjs/eslint-plugin valid styles rules, I cannot nest more than 1 level deep.
Inside '::webkite-scrollbar-thumb', however the styles are applied and everything works.

Is this expected behavior? I would assume the code either fails to compile or the styles are not applied.
Or is it possible to do this and is the eslint rule more like a suggestion to not do this.

<img width="555" alt="image" src="https://github.com/facebook/stylex/assets/14736534/0d2cb33d-8ee4-4e33-8fd7-f646f4698334">

### Expected behavior

Either the nested styles are not applied or the code fails to compile.

### Steps to reproduce

**Install necessary dependencies and add the linter to the eslint config**
```json
    "@stylexjs/eslint-plugin": "0.6.0",
    "@stylexjs/stylex": "0.6.0",
```

**Write nested styles inside ::-webkit-scrollbar-thumb**
```tsx
import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  content: {
    gridArea: 'content',
    overflowX: 'hidden',
    overflowY: 'auto',
    '::-webkit-scrollbar-thumb': {
      borderRadius: '6px',
      backgroundColor: { default: 'rgba(0, 0, 0, 0.2)', ':hover': 'rgba(0, 0, 0, 0.4)' },
    },
  },
});
```

**Comment by nmn** [comment]
This is a valid issue. You can use this as a temporary workaround:

```tsx
import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  content: {
    gridArea: 'content',
    overflowX: 'hidden',
    overflowY: 'auto',
    backgroundColor: {
      default: null,
      '::-webkit-scrollbar-thumb': { 
        default: 'rgba(0, 0, 0, 0.2)',
        ':hover': 'rgba(0, 0, 0, 0.4)',
      },
    },
    '::-webkit-scrollbar-thumb': {
      borderRadius: '6px',
    },
  },
});
```

This is obviously not idea, but it should work.

**Comment by necolas** [comment]
Surely the better workaround is to ignore the eslint-plugin's warning? Isn't the correct syntax the one in the OP, not the one in the workaround above? I think pseudo-elements shouldn't be allowed within property object-values - that doesn't really make sense to me.

**Comment by nmn** [comment]
@necolas My bad. I assumed it was a bug in the Babel plugin because it used to be a bug at one point. You're right, the best solution here is to just suppress the ESLint error.

**Comment by nedjulius** [comment]
should this be removed from the plugin?

https://github.com/facebook/stylex/blob/bea3495859da52fa1d581df409b1dac8f7e4e934/packages/eslint-plugin/src/stylex-valid-styles.js#L2481

there is a `TODO` comment that reminds to remove this suggestion as well

**Comment by nmn** [comment]
> should this be removed from the plugin?

With some extra checks to disallow it for anything *but* pseudo elements.
