### ISSUE TITLE
@stylexjs/rollup-plugin@0.7.0 tarball without lib directory

### ISSUE THREAD

**Issue by murukal** [facebook/stylex#619]
### Describe the issue

@stylexjs/rollup-plugin@0.7.0 tarball without lib directory

### Expected behavior

with lib directory

### Steps to reproduce

noop

**Comment by necolas** [comment]
@nmn the rollup-plugin package was published without a build - https://www.npmjs.com/package/@stylexjs/rollup-plugin?activeTab=code

**Comment by nmn** [comment]
Released 0.7.3 with a fix.
