### ISSUE TITLE
[@stylexjs/valid-styles]: overflow: 'clip' not allowed

### ISSUE THREAD

**Issue by slightly-askew** [facebook/stylex#620]
### Describe the issue

When I set the property `{overflow: 'clip'}` to an element, I receive an eslint error, but the style is valid and works as expected.
![CleanShot 2024-06-28 at 08 21 48](https://github.com/facebook/stylex/assets/23715191/f8653596-240d-4f7c-87c1-8b37fcba1c5f)

It also creates Typescript errors as I pass the styles around to different elements

### Expected behavior

No eslint error would be displayed by @stylexjs/valid-styles plugin 

### Steps to reproduce

install stylex 0.6.1 and  @stylexjs/valid-styles plugin 0.6.1

create a dive element and set style to `{overflow: 'clip'}`

**Comment by necolas** [comment]
`overflow:'clip'` has relatively limited [browser support](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#browser_compatibility) compared to what we typically expect of web apps today at Meta.

It might make sense to keep the eslint warning if it can be suppressed inline, or if the value `'clip'` can be allowed via eslint-plugin configuration. I don't think we want type checker errors in this case though.
