### ISSUE TITLE
@stylexjs/cli Missing Plugin

### ISSUE THREAD

**Issue by besSejrani** [facebook/stylex#624]
### Describe the issue

When I try to run the cli on a single .tsx file, I get following error

`parser/lib/index.js:10365:23) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'MissingOneOfPlugins',
  loc: Position { line: 16, column: 4, index: 324 },
  pos: 324,
  missingPlugin: [ 'jsx', 'flow', 'typescript' ]
}`

this is my stylex.json file

`{
  "input": "./src/Components/ui",
  "output": "./stylex",
  "modules_EXPERIMENTAL": ["@stylexjs/open-props"],
  "styleXBundleName": "stylex_bundle.css"
}`

One other problem, after installing the cli

I can't just use stylex directly, i need to do `npx stylex --config stylex.json` or `pnpm stylex --config stylex.json`

i get following error

`zsh: command not found: stylex`

### Expected behavior

I would expect to be able to use the cli directly, maybe configure the .json file before hand

### Steps to reproduce

- Create a .tsx component
- Install @stylexjs/cli
- Add following stylex.json config `{
  "input": "./src/Components/ui",
  "output": "./stylex",
  "modules_EXPERIMENTAL": ["@stylexjs/open-props"],
  "styleXBundleName": "stylex_bundle.css"
}
`
- Verify the error message

**Comment by nmn** [comment]
Please see the example app using the CLI. You have to use the `babelPresets` key in the configuration to enable the CLI to understand TS syntax.

We are working on adding more configuration options.

**Comment by besSejrani** [comment]
Thank you
