### ISSUE TITLE
Stop transforming textAlign:start/end

### ISSUE THREAD

**Issue by necolas** [facebook/stylex#627]
### Describe the issue

StyleX converts textAlign:start/end into CSS like this, which means those properties don't work correctly inside subtrees using the `dir` prop. This is a relatively urgent issue internally.

<img width="424" alt="image" src="https://github.com/facebook/stylex/assets/239676/667e84c5-3a3a-4722-886d-29185f053361">

We should remove this transform. (A broader task is to remove the legacy RTL selectors for style sheets altogether.)

### Expected behavior

textAlign:start/end work correctly

### Steps to reproduce

1. textAlign:end
2. See style sheet changed `end` to `right` and scoped it to `html[dir]`

**Comment by nmn** [comment]
AFAIK, this only happens in the `legacy-expand-shorthands` config which is what we use internally. (If this happens in any other config that would be a very urgent issue)

Internally we depend on this behaviour for older browsers but I think there is a way to add fallback styles for older browsers while resolving this issue.

**Comment by necolas** [comment]
end and start have been available since Chrome 1, so I don't think we need to do anything to these values - https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#browser_compatibility

**Comment by nmn** [comment]
This is news to me. Let me make this change immediately then.
