### ISSUE TITLE
stylex.firstThatWorks() not correctly linted

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#641]
### Describe the issue

<img width="840" alt="image" src="https://github.com/user-attachments/assets/19d7b3a3-76be-4d70-8735-5104c73d7290">

### Expected behavior

No eslint error.

### Steps to reproduce

Take the example in the doc:

https://stylexjs.com/docs/api/javascript/firstThatWorks/

```tsx
import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  header: {
    position: stylex.firstThatWorks('sticky', '-webkit-sticky', 'fixed'),
  },
});
```

**Comment by necolas** [comment]
We probably wouldn't allow vendor prefixed values in source code, and instead rely on polyfills

**Comment by olivierpascal** [comment]
I intend to use this as a default fallback for a css variable: https://github.com/facebook/stylex/issues/432

**Comment by necolas** [comment]
Does this issue reproduce with a variable instead then? Give the code you shared, the lint message looks correct to me
