### ISSUE TITLE
Can I use stylex in Next.JS with SWC?

### ISSUE THREAD

**Issue by Redish101** [facebook/stylex#643]

**Comment by nmn** [comment]
You can with the CLI

**Comment by Dwlad90** [comment]
https://github.com/facebook/stylex/issues/70#issuecomment-2247551735

**Comment by nmn** [comment]
@Redish101 Look at the linked comment above.

**Comment by Redish101** [comment]
> https://github.com/facebook/stylex/issues/70#issuecomment-2247551735

Wow, that's cool!
