### ISSUE TITLE
[@stylexjs/webpack-plugin] Yarn Plug'n'Play   Cannot find package  '@babel/plugin-transform-modules-commonjs'

### ISSUE THREAD

**Issue by hotlif** [facebook/stylex#654]
### Describe the issue

Cannot find package '@babel/plugin-transform-modules-commonjs' 

see https://github.com/facebook/stylex/commit/1e0933c6b543730974f2cf1f66c2d74defaf938d#diff-ca9a5ec2c1a865ca7d717cfaed22c11c91459fefce687dccc92ca910c1409c5eR237

### Expected behavior

I hope this error message will not be prompted

### Steps to reproduce

1. git clone https://github.com/facebook/stylex
2. cd apps/webpack-example
3. corepack enable && yarn set version stable
4. yarn && yarn build

**Comment by hotlif** [comment]
@nmn Any suggestions?

**Comment by nmn** [comment]
Start by testing https://www.npmjs.com/package/stylex-webpack

The webpack plugin has many issues and fixing it might take longer than trying this other plugin.
