### ISSUE TITLE
Inefficient and Confusing Use of StyleX for Color Scheme Handling

### ISSUE THREAD

**Issue by jsonchou** [facebook/stylex#661]
### Describe the feature request

It is heavily used throughout the entire document.

``` js
const DARK = '@media (prefers-color-scheme: dark)';
const LIGHT = '@media (prefers-color-scheme: light)';
``` 

If you use dynamic color scheme switching, in this case, using StyleX is a complete disaster.

The entire project is full of this garbage code:

``` html

<div 
{...stylex.props(s.box, scheme === 'dark' ? [bg.darkBgColor1, bd.dark2] : [bg.lightBgColor1, bd.light2] 
/>

```

Besides using @media (prefers-color-scheme: dark), are there more viable use cases, such as supporting external variables and do not generate css segments as StyleX way:

``` css

box:{
 backgroundColor: 'var(--mantine-color-1)', // from mantine
}

:root
:root[data-mantine-color-scheme=light]
:root[data-mantine-color-scheme=dark]
```

Everywhere else it's visually pleasing, but when it comes to backgroundColor and color, it's simply maddening.

**Comment by jsonchou** [comment]
So many errors, making it difficult to move forward.

TypeError: Cannot read properties of undefined (reading 'watcher')

I strongly do not recommend StyleX at this moment.

**Comment by nmn** [comment]
I don't understand the question.

**Comment by jsonchou** [comment]
@nmn 

One common method involves using media queries to adapt the theme to the system's color scheme settings. For instance:

``` css
const DARK = '@media (prefers-color-scheme: dark)';
const LIGHT = '@media (prefers-color-scheme: light)';
```

This approach allows the page to automatically switch between dark and light modes according to the user's system settings.

However, many websites prefer to manage themes through custom solutions using local storage mechanisms such as cookies or localStorage. For example, the `Mantine` library employs a data attribute on the <html> tag to store and apply the user's chosen color scheme:

```html
<html data-mantine-color-scheme={getStoredColorScheme()} >
```

In this setup, theme-specific styles are defined as follows:



```css
:root[data-mantine-color-scheme=light] {
  /* Light theme styles */
}

:root[data-mantine-color-scheme=dark] {
  /* Dark theme styles */
}

```

On the other hand, with `StyleX`, applying themes requires a more manual approach. You need to explicitly define styles based on the user's chosen color scheme. For example:

```jsx
<div 
  {...stylex.props(s.box, scheme === 'dark' ? [bg.darkBgColor1, bd.dark2] : [bg.lightBgColor1, bd.light2])}
/>
```

In this case,`StyleX` necessitates specifying the styles directly for each theme variant, which can result in more verbose code compared to libraries that use data attributes or media queries for theme management.


Is there a better way to avoid redundant color scheme logic checks, or i missed something.

**Comment by nmn** [comment]
> Is there a better way to avoid redundant color scheme logic checks, or i missed something.

The modern solution to this problem is to use the `light-dark()` function. This greatly simplifies defining light and dark themes and controlling them manually using the `color-scheme` style property.


```tsx
export const colors = stylex.defineVars({
  primaryText: 'light-dark(black, white)',
  secondaryText: 'light-dark(#333, #ccc)',
  accent: 'light-dark(blue, lightblue)',
  background: 'light-dark(white, black)',
  lineColor: 'light-dark(gray, lightgray)',
});
```

Now on your `html` element, you can simply set the `color-scheme` value to control which colors are used.

```css
:root {
  /* System Theme */
  color-scheme: light dark;
}
:root.light-theme {
  color-scheme: light;
}
:root.dark-theme {
  color-scheme: dark;
}
```
