### ISSUE TITLE
add ability to create css file per `stylex.create`

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/stylex#679]
### Describe the feature request

With React 19 https://react.dev/blog/2024/04/25/react-19#support-for-metadata-tags

being able to dedupe link tags this could be a pretty powerful feature by only ever including the exact styles you need for a page

with remix, it could apply each to a page via `import buttonSheet from './components/button.style.css` and then add each component's css to the `links` function

**Comment by necolas** [comment]
I don't think that feature has any benefits for stylex, and that way of using it isn't really the intended use case. You still don't want new css getting loaded before different bits of ui can render, from the client or server

**Comment by nmn** [comment]
Just wanted to chime in and say that with atomic styles the total size of the CSS is already nearly ideal so you wouldn't actually gain any performance improvements with what you're asking for.

And atomic styles are required to make half the features of StyleX work.

**Comment by lifeiscontent** [comment]
Sure, it was just an idea. If you don't think chiming in on this kind of stuff I'll refrain from suggestions in the future.
