### ISSUE TITLE
cannot reset `content` attribute for `::before`

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/stylex#681]
### Describe the issue

given the following style:

```
{
    content: {
      ":last-of-type::before": "unset",
    },
    "::before": {
      content: "''",
      height: "100%",
      width: 1,
      backgroundColor: colors.outline3,
      left: 36,
      position: "absolute",
    },
}
```

I cannot unset the content attribute because it has a lower priority

### Expected behavior

I'd expect to be able to clear out the before element

### Steps to reproduce

use the style, and you'll see

**Comment by necolas** [comment]
I don't know why you'd expect content to be unset with this code, especially since you're using 2 different syntaxes to target the same pseudo element and property. Stylex doesn't support `last-of-type` selectors either

**Comment by lifeiscontent** [comment]
@necolas I could use `:last-child` as well, the point is `unset` in stylex renders as `"unset"` instead of `unset`

**Comment by nmn** [comment]
`content` is special-cased to wrap strings in quotes. We could also special case `unset` and other similar keywords to not be wrapped in quotes, however, we explicitly discourage the usage of pseudo elements like `::before` and suggest using real divs instead.

What is your use-case for needing pseudo elements specifically along with complex positional selectors?

**Comment by lifeiscontent** [comment]
@nmn basically using it for a timeline view where a 1px width `::before` flows down through each timeline item except for the last one

**Comment by nmn** [comment]
@lifeiscontent as the docs state, we recommend using the logic in your components to conditionally render content instead of using selectors such as `:last-of-type`.
