### ISSUE TITLE
ESLint rule trips up on nested objects within at-rules such as `@starting-style`

### ISSUE THREAD

**Issue by nikeee** [facebook/stylex#698]
### Describe the feature request

I tried to use [`@starting-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style) and I think StyleX doesn't support it (yet)? Is something like this on the roadmap?

**Comment by nmn** [comment]
It should already work, but we should update the ESLint rule to allow it and ensure it's ordered correctly in the generated CSS.

**Comment by nikeee** [comment]
I think the minimum repo is this:

```js
const stylesErr = stylex.create({
	base: {
		width: {
			default: 800,
			'@media (min-width: 1540px)': {
				default: 10,
				":hover": 20,
			},
			"@starting-style": {
				// error
				default: 10,
				":hover": 20,
			}
		},
	},
});
```

However, this works:
```js
const stylesOk = stylex.create({
	base: {
		width: {
			default: 800,
			'@media (min-width: 1540px)': {
				default: 10,
				":hover": 20,
			},
			// ok
			"@starting-style": 10
		},
	},
});
```

While browsing the source for a PR this week, I suspect that it may be missing in this list (though I'm not sure and I didn't test it):
https://github.com/facebook/stylex/blob/1a18bd58330fc538c1b1e0a5b8f5680f7aaee3d5/packages/eslint-plugin/src/stylex-valid-styles.js#L2261-L2265

Maybe it's just a linter issue because the resulting CSS seems to work as intended.

**Comment by nmn** [comment]
It is a linter issue and it's not specific to `@starting-style`. Thanks for the bug report will investigate.

**Comment by nmn** [comment]
There is a high chance that adding `@starting-style` to the list of know at-rules and pseudo-classes will fix this issue.

**Comment by nikeee** [comment]
That seems to be the case. I added a regression test and filed a PR: #703
