### ISSUE TITLE
Update `dev-runtime` to export a patched `stylex`

### ISSUE THREAD

**Issue by nmn** [facebook/stylex#719]
Today, the the `@stylexjs/dev-runtime` package exports a single `inject` function that monkey-patches the `@stylexjs/stylex` package to be able to work at runtime.

Update the package so that it can be used *instead of* the `@stylexjs/stylex` package.

It should be possible to import the entire StyleX API from `@stylexjs/dev-runtime`.

## One Open Question

It is possible to change some configuration settings for StyleX. What is the best way to handle this configuration in the dev runtime? There are two possible options here:

Export an extra function called `configure` that lets you define the settings and then it can be developer's responsibility to make sure that `configure` is called *before* any other StyleX API is used.

OR...

We could make `configure` return the entire StyleX API, and the developer is then expected to define a single file with a configuration and then use the API from that file in the rest of the codebase.

If we can enable the first path, that would be preferable as it would be easy to find-replace the package name once the build steps are set up.

**Comment by necolas** [comment]
Could the babel plugin be configured to set what the runtime is by rewriting the import? Then there's no need for another config?

**Comment by nmn** [comment]
The babel plugin can already be configured to inject function calls that inject styles at runtime. It automatically insert an import for the function that injects styles at runtime that is otherwise not part of the `@stylexjs/stylex` runtime.

So if you're using Babel, you don't need to use `dev-runtime`.

---

The only value of the `dev-runtime` is the ability to use StyleX without setting up *any* build steps or code transformations. It happens to re-use most of the code from the `shared` package or it wouldn't be worth maintaining at all.

**Comment by sudheerDev** [comment]
@nmn Can you assign this to me? I want to take have a look at this.

**Comment by nmn** [comment]
Fixed in #746
