### ISSUE TITLE
[website] Add a "brand" page to the website

### ISSUE THREAD

**Issue by nmn** [facebook/stylex#733]
Add a basic "brand" page for the website where the logos of StyleX can be downloaded in various configurations.

Also, right clicking the logo in the nav-bar should open the brand page.

**Comment by p0nch000** [comment]
I'll work on this, can somebody please send me the logos plss

**Comment by nmn** [comment]
In #756 I've added a couple of additional "large" SVG assets that can be used for this. There were already "small monochrome" variants available along with an SVG favicon.

I'll soon follow-up with "small multi-color" variants of the logo which we doesn't exist yet, but probably should.
