### ISSUE TITLE
An API to define "base styles"

### ISSUE THREAD

**Issue by nmn** [facebook/stylex#738]
Add a new API to StyleX for defining "base styles". This API would be very similar to `stylex.create`, but instead of generating atomic styles, this would create a typical "bag of styles" className Rule.

Base styles would have the lowest specificity in the generated styles other than the rules that define the default values for variables.

The types of `stylex.props` and `stylex.attrs` would need to be updated to conditionally allow a "base style" to be passed in as the first argument only.

---

## Why?

Atomic styles have many desirable qualities:
- They result in a re-usable minimal CSS file
- They enable seamless style composition

However, there is *one* performance bottleneck with atomic styles. As the average number of classNames per HTML element grows, the amount of work that the browser needs to do to resolve those styles grows as well.

In certain cases where extremely long lists are rendered where all items in the list have mostly the same styles but not entirely so, using atomic styles can have a noticeable performance impact.

Adding an API to define "base styles" for such cases will provide an escape hatch to optimise the style resolution performance in certain scenarios at the cost of a slightly larger CSS bundle.

## Could this be automated?

We considered a system where the compiler could detect styles that are commonly used as the first argument to `stylex.props` and automatically generating "base styles" to replace them at compile time.

Not only would this compilation process be extremely difficult (it would require at least two passes over the codebase to start working), it wouldn't solve the problem well. To actually solve
the underlying performance problems, we don't need to find the styles that are used in many components, but the styles that are rendered *a lot*.

Doing *this* automatically would involve profiling the actual web app to find styles that are rendered most often and not something that is easy to automate.

## CSS Resets?

This API *would not* add support for arbitrary selectors and would not be an API for defining CSS resets. Those will continue to belong in a normal CSS file.

## Example

```ts
// baseStyles.ts
export const absFill = stylex.createBaseRule({
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  boxSizing: 'border-box',
  contain: 'strict',
  overflow: 'hidden',
});
```

```tsx
import {absFill} from './baseStyles';

const styles = stylex.create(...);

<div {...stylex.props(absFill, styles.card, isActive && styles.active, ...} />
```

NOTE: using `absFill` anywhere other than the first argument to `stylex.props` will result in a type error (or a runtime error)

NOTE: The example shows `stylex.createBaseRule` creating a single rule rather than a set of rules like `stylex.create` because we expect this API to usually be exported from one central location, and we would want to take advantage of tree-shaking, if possible.

**Comment by nonzzz** [comment]
Awesome! But the transform result is what? Is there any transformed result here?

**Comment by nonzzz** [comment]
In my opinion the demo generate result may look like

```jsx

// bag-style can be used anywhere. Only generate once

<div className="bag-style xxhash1 xxhash2" />

```

```css

.bag-style { ... }

.xxhash {...}

```

**Comment by necolas** [comment]
I don't know if this is worth doing. I built an API like this into RNfWeb, where I first discovered the layout cost of atomic styles many years ago. But it was private to the library. Making a public API is bound to introduce complexity and confusion.

I don't think we've really noticed this cost as a significant issue in Meta apps. And it's one of those things we can expect / encourage Chrome to improve (if it moves the needle) simply because it's in use on heavily used websites like those built by Meta. So the question is really whether this is worth dedicating ongoing time and effort vs other higher impact perf changes.

**Comment by nmn** [comment]
@necolas I, too, really dislike the idea of adding this API and would like to avoid it if possible.

There have been some isolated incidents where we've had noticeable cost in certain internal pages at Meta.

I'm willing to wait for the browsers to optimise this use-case and wait for now.

**Comment by nmn** [comment]
The risk of base style proliferation is too high and so this is probably a bad idea.

Closing this issue and will continue to think of other ways of solving this issue.
