### ISSUE TITLE
Help wanted to understand a specificity clash with a css reset

### ISSUE THREAD

**Issue by hmerritt** [facebook/stylex#753]
### Describe the issue

I am using StyleX and also have a css reset.

Even though I have styles directly being applied via a class from styleX, the _generic catch-all_ css from the reset is being applied.

> Screenshot showing [left] the `h1` with styleX classes, and [right] the classes being overruled
![image](https://github.com/user-attachments/assets/8db5c3c4-da15-4fc7-a958-ef7db37f2c64)

> Screenshot showing [right] the generic css from the reset being applied
![image](https://github.com/user-attachments/assets/502900ff-f746-4201-a0fc-2fcd28acee49)

### Expected behavior

I would have thought the specificity of a class from styleX would be the active style, but it's not, it's the css reset.

### Steps to reproduce

css reset: https://github.com/hmerritt/adrift/blob/feat/stylex/src/lib/styles/global/reset.scss

h1 being rendered: https://github.com/hmerritt/adrift/blob/de80c4ac8189a6880a33e03f2831d2b6fafd6c09/src/view/routes/index.tsx#L27

### Test case

n/a

### Additional comments

(this is _probably_ not a bug and most likely my misunderstanding, but I would love to know why this is happening)

**Comment by Jta26** [comment]
I think the issue is that you styles are layered with `@layer` somewhere.

If you look at the styles in the first screenshot above every style it says "Layer priority3".

Could this be the reason?

In CSS layers are considered before calculating specificity weights

**Comment by hmerritt** [comment]
I did notice the `Layer priority3` too... that could well be it... although it's not something I have done intentionally and am not sure how to change it

**Comment by necolas** [comment]
You can either add your reset to a lower priority layer, or set `useCSSLayers:false` in the vite plugin config that you appear to be using - https://github.com/HorusGoul/vite-plugin-stylex/blob/main/packages/vite-plugin-stylex/src/main.mts#L77

**Comment by hmerritt** [comment]
Aaha! - that's worked 🎉 - completely missed the `useCSSLayers` prop, thanks for that
