### ISSUE TITLE
[hash] in fileName

### ISSUE THREAD

**Issue by oudmane** [facebook/stylex#778]
### Describe the feature request

Hello, I'm using the rollup plugin and I went to output the css file with a hash, I tried adding `[hash]` in `fileName` but it doesn't get replaced by a hash, can this feature be supported, if yes, how to do it (I can also implement it and make PR).

Many thanks.

```js
import stylexPlugin from '@stylexjs/rollup-plugin';

const config = {
  input: './index.js',
  output: {
    file: './.build/bundle.js',
    format: 'es',
  },
  // Ensure that the stylex plugin is used before Babel
  plugins: [stylexPlugin({
    // Required. File path for the generated CSS file.
    fileName: './.build/stylex.[hash].css',
    // default: false
    dev: false,
    // prefix for all generated classNames
    classNamePrefix: 'x',
    // Required for CSS variable support
    unstable_moduleResolution: {
      // type: 'commonJS' | 'haste'
      // default: 'commonJS'
      type: 'commonJS',
      // The absolute path to the root directory of your project
      rootDir: __dirname,
    },
  })],
};

export default config;
```

**Comment by nmn** [comment]
This feature is not currently supported.

> I can also implement it and make PR

Yes please!

**Comment by yousoumar** [comment]
Hi [@nmn](https://github.com/nmn)! Can I work on this since there is no response since? If so, please assign it to me.

**Comment by nmn** [comment]
@yousoumar There's many other issues that are up for grabs if you're looking for something. It's been less than a week so I would like to give @oudmane more time.
