### ISSUE TITLE
[Bundlers] Investigate creating a postCSS plugin to create more reliable Bundler integrations

### ISSUE THREAD

**Issue by nmn** [facebook/stylex#779]
### Describe the feature request

See: https://github.com/facebook/react-strict-dom/issues/34#issuecomment-2493900014

There are community efforts using a PostCSS plugin to create a Webpack plugin that works reliably in more scenarios, including Next.js.

Our current Next.js plugin is not of a high-enough quality and leads to many issues during development. A better implementation that works reliably is a big need at the moment and the results so far are promising.

@javascripter would you be interested in tackling this?

**Comment by javascripter** [comment]
@nmn Yes, and I've submitted [a PR](https://github.com/facebook/stylex/pull/781).
