### ISSUE TITLE
Add dynamic styles to benchmarks fixture

### ISSUE THREAD

**Issue by necolas** [facebook/stylex#799]
### Describe the feature request

We don't have any dynamic styles syntax in the fixture data used by the bundle-size benchmark. This means we don't capture the impact on generated CSS from the current approach to implementing dynamic styles.. Include a significant number of dynamic styles in the fixture to resolve this issue.

**Comment by Samantha-Zhan** [comment]
I can attempt this task if no one is on it since it relates to a previous task I was working on. However, I haven't worked with benchmarks fixture before, would you mind give me some pointers on where to get started?

**Comment by necolas** [comment]
These are the relevant files/scripts:

* The rollup-example app contains a (very big) fixture called [`lotsOfStyles.js`](https://github.com/facebook/stylex/blob/main/apps/rollup-example/lotsOfStyles.js)
* The [benchmark workflow](https://github.com/facebook/stylex/blob/main/.github/workflows/performance.yml) builds the packages/apps.
* It then calls the [size.js script](https://github.com/facebook/stylex/blob/main/packages/scripts/size.js) (which you can also run locally)
* The size script generates size data using the build in the rollup example.

If we add [dynamic styles](https://stylexjs.com/docs/learn/styling-ui/defining-styles/#dynamic-styles) to the `lotsOfStyles.js` file, we should see an increase in the rollup bundle size data generated by the script. Maybe simplest to add a large block of dynamic styles at the bottom of the fixture, but open to suggestions.

**Comment by nmn** [comment]
Thanks for taking this on @Samantha-Zhan!

The benchmark script has been flaky recently so this task might involve a bit of investigation to figure out why and to fix it.

**Comment by nmn** [comment]
@Samantha-Zhan The flakiness is with the github action specifically, not the script itself. When you're done with your PR that's when that will become relevant.

**Comment by necolas** [comment]
I don't think it's flakey. It doesn't run on PR's from forks

**Comment by Samantha-Zhan** [comment]
@necolas I added some styles inside the `lotsOfStyles.js` fixture, and was trying to rebuild the `script.js` file. What I did:
- `npm install --save-dev @stylexjs/rollup-plugin`
- 1npm run build`
However, I got following error on build:
```
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
@stylexjs/stylex (imported by "index.js" and "lotsOfStyles.js")
[!] (plugin rollup-plugin-stylex) SyntaxError: Invalid @ rule body
undefined (1:38)
    at Object.generateBundle (file:///Users/samzjq/Documents/stylex/packages/rollup-plugin/lib/es/index.mjs:40:13)
    at /Users/samzjq/Documents/stylex/node_modules/rollup/dist/shared/rollup.js:1087:40
```
Don you know what might have went wrong?

**Comment by Samantha-Zhan** [comment]
The error was actually caused by [`index.js` file](https://github.com/facebook/stylex/blob/main/apps/rollup-example/index.js#L15), which is called inside [`rollup.config.mjs` build script](https://github.com/facebook/stylex/blob/main/apps/rollup-example/rollup.config.mjs#L13) to create the bundle, **basically dynamic style NEED a parameter to be passed and can't be called like this**:
```
const styles = lotsOfStyles.map((defs) => Object.values(defs));
```
I'm trying to see if there is a workaround to this.

**Comment by Samantha-Zhan** [comment]
[blocked] for some unknown reason, regardless of what error that occur during executing [index.js file](https://github.com/facebook/stylex/blob/main/apps/rollup-example/index.js#L15) by calling rollup script `npx rollup --config ./rollup.config.mjs`, it prints the exact same error message (see above).
Hence, I can't figure out why a small change in index.js makes the rollup fail:
```
import stylex from '@stylexjs/stylex';
import { lotsOfStyles } from './lotsOfStyles';

const styles = lotsOfStyles.map((defs) => Object.values(defs));
const lotsOfStylesDynamic = [
  stylex.create({
   // PASS
    bottom12: {
      paddingBottom: 12,
    },
   // FAIL
    dynamic: (opacity) => ({
      opacity,
    }),
  }),
];

export default function App() {
  return stylex.props(styles, dynamicStyles);
}
```

**Comment by necolas** [comment]
I was able to reproduce the issue. Looks like the rollup plugin is buggy and doesn't support dynamic styles syntax? The error and error message is not clearly related to the change that triggers the error

```
[!] (plugin rollup-plugin-stylex) SyntaxError: Invalid @ rule body
undefined (1:39)
```

**Comment by Samantha-Zhan** [comment]
I tried adding a console log at `rollup.js` and found more information about this error:
```
SyntaxError: Invalid @ rule body
    at Object.generateBundle (file:///Users/samzjq/Documents/stylex/packages/rollup-plugin/lib/es/index.mjs:40:13)
    at /Users/samzjq/Documents/stylex/node_modules/rollup/dist/shared/rollup.js:1088:40 {
  fileName: 'stylex.css',
  source: '@property --opacity { inherits: false }\n' +
    '.xa0d40w:not(#\\#){opacity:var(--opacity)}\n' +
    '.xsag5q8:not(#\\#):not(#\\#){padding-bottom:12px}',
  loc: { line: 1, column: 39 },
  data: { type: 'AtRuleBodyInvalid' }
}
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
@stylexjs/stylex (imported by "index.js")
[!] (plugin rollup-plugin-stylex) SyntaxError: Invalid @ rule body
undefined (1:39)

```

Since it says error occurred on first line; I suspect it may because instead of `@property --opacity { inherits: false }\n`, it should be `@property --opacity { inherits: false; }\n`, which relate to adding inherit property to dynamic style [here](https://github.com/facebook/stylex/pull/794/commits). However, when I tried to modify [packages/babel-plugin/src/visitors/stylex-create/index.js](https://github.com/facebook/stylex/pull/794/files#diff-879871ad922cfbbd8d59d46cd33adfccaa6305fb88c5b22dfdd5c06f5c945bf5) file, the change doesn't get reflected when I rerun rollup 🤔

**Comment by Samantha-Zhan** [comment]
[RESOLVED]
The cause of the error is that we are missing mandatory descriptors `syntax` and `initial-value` for `@property` (see MDS docs [@property](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) [initial-value](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/initial-value) [syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax))
Hence, we should declare the following in [packages/babel-plugin/src/visitors/stylex-create/index.js](https://github.com/facebook/stylex/pull/794/files#diff-879871ad922cfbbd8d59d46cd33adfccaa6305fb88c5b22dfdd5c06f5c945bf5):
```
injectedInheritStyles[fnsName] = {
          priority: 0,
          ltr: `@property ${fnsName} { syntax: "*"; inherits: false; initial-value: "*";}`,
          rtl: null,
        };
```
I will create a follow up PR to fix this
